### ISSUE TITLE
Entity not received by daemon if total size exceeds 64KB

### ISSUE THREAD

**Issue by sebarosales** [aws/aws-xray-sdk-dotnet#1]
**STEPS TO REPRODUCE THE ISSUE**
1) BeginSegment
2) BeginSubsegment
3) AddMetadata (optional, but it makes the reproduction easier if large metadata is added, for example 32KB)
4) EndSubsegment
5) Repeat steps 2 to 4 until total segment size is greater than 64KB (for example, 2 subsegments with 32KB of metadata)
6) EndSegment

According to documentation (https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html#api-segmentdocuments-subsegments), a segment document can be up to 64 KB, but subsegments can be sent separately to avoid exceeding the maximum segment document size. This scenario should work. However, you can see that the daemon does not receive the segment.
I found in the code that ProcessEndSegment method sends the entire segment to the daemon (on step 6), and that single document exceeds 64KB. The subsegments here should be sent separately.

As a workaround I changed the constant MaxSubsegmentSize from 100 to 1. That forces each subsegment to send immediately after calling EndSubsegment, as ShouldStreamSubsegments returns true. This works as expected for this case, but it is not optimal if the subsegments are small enough to fit into one single document.

**Comment by yogiraj07** [comment]
Hi @sebarosales,
 
Thank you for the post.
 
We send segments/subsegments over UDP to the local X-Ray daemon. UDP packets are limited to 64KB in size which resulted in your segment (that contains all your subsegments) being rejected by daemon. You can get more insights by setting up logger. Please refer [Link]( https://github.com/aws/aws-xray-sdk-dotnet/tree/master#logging-net).
 It would be possible for the SDK to automatically apply subsegment streaming to large segments. However, the segment size in bytes is not known until the segment JSON document has been serialized to a string - a relatively expensive operation. For reference : https://github.com/aws/aws-xray-sdk-java/issues/4
 
Recommended solution : setting MaxSubsegmentSize is the correct way for your use case.
 
I am closing this issue, please feel free to reopen, if you have any questions.
 
Thanks,
Yogi

**Comment by sebarosales** [comment]
Hi Yogi,

Thanks for your answer.

Currently MaxSubsegmentSize is a constant and the only way to change it is to modify and recompile the code. This makes the process of keeping the SDK updated much more complicated.

¿Could it be a setting?

**Comment by yogiraj07** [comment]
Hi @sebarosales ,
We appreciate your feedback and have included this in our backlog. 

Thanks,
Yogi
