### ISSUE TITLE
Add the ability to add additional attributes to the http segment

### ISSUE THREAD

**Issue by richardgavel** [aws/aws-xray-sdk-dotnet#10]
It would be useful to be able to add additional attributes to the http segment that we might want to pull from the request, such as specific cookie values, claims from a header token (or other header information), etc. This would have an impact, I assume, on the filtering within the XRay UI to be able to filter by those additional attributes.

**Comment by yogiraj07** [comment]
Hi @richardgavel ,

We have adding annotations capability for segment/subsegment , which you can leverage to store desired information about http request.

Annotations are indexed for use with filter expressions.

Please refer :  https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-dotnet-segment.html

Let us know if you have any questions.

Thanks,
Yogi

**Comment by Caldas** [comment]
Indeed @yogiraj07 I'm using annotations a lot !!

sample for `application` (system that calls my Audit system) extracted from request header
![image](https://user-images.githubusercontent.com/938045/36919617-b3355f32-1e3c-11e8-9a8a-2ee17e5a4df9.png)

**Comment by yogiraj07** [comment]
Hi @richardgavel ,
Closing this issue. Feel free to reopen, if you have any questions. 

Best,
Yogi
