### ISSUE TITLE
SDK invocations subsegments are not used as parentId in request header

### ISSUE THREAD

**Issue by miokowpak** [aws/aws-xray-sdk-dotnet#104]
I think this is a bug, but, its possible that its intended behaviour.

In `XRayPipelineHander::ProcessBeginRequest`, it appears that trace header on the request is being set before a subsegment is created for the SDK function invocation.

In my case, I'm using an SQS queue for communication between two services.  The result is that the sending service is recorded as the parent of the `SendMessage` invocation, and also as the parent of the trace in the receiving service.

My assumption was that the subsegment created for the `SendMessage` invocation would be recorded as the parent in the trace header such that my service map would show that the parent of the receiving service is the SQS queue, not the first service.

Please let me know if I've assumed incorrectly.  If I am correct and this should be changed, I'm more than happy to put together a PR.

**Comment by srprash** [comment]
Hi @miokowpak ,
I would be happy to take a look into this issue. Could you give some more details on your use case? If you could provide the code snippet for your receiving service polling the SQS and the service map if possible, it would help me understand the issue better. 
Thanks

**Comment by miokowpak** [comment]
@srprash thanks for the quick reply.

Simply put, our use case is that a user clicks a button on a website.  The website puts a message on an SQS queue, and, it is eventually processed by a back end server.  This is one small part of a much larger legacy system that we're trying to instrument.

My expectation was that the service map would include `web -> sqs -> server`, but instead, I get `sqs <- web -> server`.

If the behaviour I am seeing is what is expected, please just let me know and feel free to close, and accept my apologies for misunderstanding.

My receiving code is actually split between a few classes in two repos, but, essentially, it is doing the following:

```
ReceiveMessageRequest request = new ReceiveMessageRequest()
{
    QueueUrl = this.QueueUrl,
    MaxNumberOfMessages = this.NumberOfMessagesToGet,
    AttributeNames = new List<string> { "AWSTraceHeader" },
};

var response = this.SQS.ReceiveMessage(request);
            
foreach (Amazon.SQS.Model.Message msg in response.Messages)
{
    string traceHeader;
    if (msg.Attributes.TryGetValue("AWSTraceHeader", out traceHeader))
    {
        TraceHeader traceHeader = TraceHeader.FromString(msg.TraceHeader);
        AWSXRayRecorder.Instance.BeginSegment("server", traceHeader.RootTraceId, traceHeader.ParentId, new SamplingResponse(SampleDecision.Sampled));
    }
    
    ...
    
    AWSXRayRecorder.Instance.EndSegment();
}
```

For what its worth... the real code properly uses `try`/`catch`/`finally` and does all the proper things.

Below is the raw data from my trace.  I have removed unrelated segments and subsegments and any identifying information, please let me know if you need more details than provided:

```
{
  "Duration": 73.224,
  "Id": "1-5d8bff80-000000000000000900005953",
  "Segments": [
    {
      "Document": {
        "id": "a7ccedc05fe6a678",
        "name": "web",
        "start_time": 1569602368.855198,
        "end_time": 1569602372.881767,
        "aws": {
          "xray": {
            "sdk": "X-Ray for .NET",
            "sdk_version": "2.6.1"
          }
        },
        "service": {
          "runtime": ".NET Framework",
          "runtime_version": "4.0.30319.42000"
        },
        "trace_id": "1-5d8bff80-000000000000000900005953",
        "subsegments": [
          {
            "id": "b91fc4cd2a486ea5",
            "name": "Button",
            "start_time": 1569602368.856197,
            "end_time": 1569602372.881767,
            "subsegments": [
              {
                "id": "4ad0c87c0fca4183",
                "name": "SQS",
                "start_time": 1569602369.448848,
                "end_time": 1569602369.507499,
                "http": {
                  "response": {
                    "status": 200,
                    "content_length": 378
                  }
                },
                "aws": {
                  "region": "us-east-1",
                  "message_id": "56e9df00-06b3-4dfc-95bd-1f6bb7585027",
                  "delay_seconds": 0,
                  "request_id": "8119c75c-73df-524c-aacb-91544e5edc37",
                  "operation": "SendMessage",
                  "message_attribute_names": {
                    "Count": 0
                  },
                  "queue_url": "https://sqs.us-east-1.amazonaws.com/accountid/queuename",
                  "resource_names": [
                    "https://sqs.us-east-1.amazonaws.com/accountid/queuename"
                  ]
                },
                "namespace": "aws"
              }
            ]
          }
        ]
      },
      "Id": "a7ccedc05fe6a678"
    },
    {
      "Document": {
        "id": "c2c15c6c3b2b8f76",
        "name": "server",
        "start_time": 1569602375.41632,
        "end_time": 1569602376.228504,
        "parent_id": "b91fc4cd2a486ea5",
        "aws": {
          "xray": {
            "sdk": "X-Ray for .NET",
            "sdk_version": "2.6.1"
          }
        },
        "service": {
          "runtime": ".NET Framework",
          "runtime_version": "4.0.30319.42000"
        },
        "trace_id": "1-5d8bff80-000000000000000900005953"
      },
      "Id": "c2c15c6c3b2b8f76"
    },
    {
      "Document": {
        "id": "310596520a2789c4",
        "name": "SQS",
        "start_time": 1569602369.448848,
        "end_time": 1569602369.507499,
        "parent_id": "4ad0c87c0fca4183",
        "inferred": true,
        "http": {
          "response": {
            "status": 200,
            "content_length": 378
          }
        },
        "aws": {
          "region": "us-east-1",
          "message_id": "56e9df00-06b3-4dfc-95bd-1f6bb7585027",
          "delay_seconds": 0,
          "request_id": "8119c75c-73df-524c-aacb-91544e5edc37",
          "operation": "SendMessage",
          "message_attribute_names": {
            "Count": 0
          },
          "queue_url": "https://sqs.us-east-1.amazonaws.com/accountid/queuename",
          "resource_names": [
            "https://sqs.us-east-1.amazonaws.com/accountid/queuename"
          ]
        },
        "trace_id": "1-5d8bff80-000000000000000900005953",
        "origin": "AWS::SQS::Queue",
        "subsegments": [
          {
            "id": "21335e7009ebf2dc",
            "name": "QueueTime",
            "start_time": 1569602369.448848,
            "end_time": 1569602369.507499
          }
        ]
      },
      "Id": "310596520a2789c4"
    }
  ]
}
```

Considering the raw trace, my expectation was that the `parent_id` of the `server` segment would be `310596520a2789c4`.  As I mentioned, looking at the `XRayPipelineHandler`, I understand why its not this value... I'm just not yet convinced that what it is doing is correct.

Thanks

**Comment by srprash** [comment]
Hi @miokowpak ,
Thanks for the details. I was able to reproduce the issue from your use case.
> In XRayPipelineHander::ProcessBeginRequest, it appears that trace header on the request is being set before a subsegment is created for the SDK function invocation.

You are right about the cause of the problem. PRs are always welcome and much appreciated.
Thank you!

**Comment by miokowpak** [comment]
Thanks for the feedback.  Not sure if I'll be able to do this during work time or if its going to have to be personal time.  Either way, I'll do my best to submit a PR by the end of next week.
