### ISSUE TITLE
X-Ray integration via serverless.yml is not happening using .Net core sdk

### ISSUE THREAD

**Issue by neetika123** [aws/aws-xray-sdk-dotnet#107]
Hi,
I am developing a microservice using .NET core 2.2, trying to integrate x-ray via serverless.yml but its not working. no error but not result at X-ray . Below is the code description.
serverless.yml
provider:
  name: aws
  tracing: 
    lambda: true
functions:
  GetPersonsAsync:
    handler: xyz-abcd
    name: dfdfdfdfd
    description: provide your lambda function description here
    tracing: Active

====C# code for Handler=======
 public async Task<APIGatewayProxyResponse> GetPersonsAsync(APIGatewayProxyRequest request, ILambdaContext context)
        {
            AWSSDKHandler.RegisterXRayForAllServices();
            AWSXRayRecorder.Instance.BeginSubsegment("GetPersonsData");
====business logic=========
}

====IAM permissions=========
 "Effect": "Allow"
        },
        {
            "Resource": [
                "*"
            ],
            "Action": [
                "xray:BatchGetTraces",
                "xray:PutTelemetryRecords",
                "xray:GetTraceGraph",
                "xray:GetServiceGraph",
                "xray:GetTraceSummaries",
                "xray:PutTraceSegments"
            ],
            "Effect": "Allow",
            "Sid": "sdadfsdsds"
        },
        {
            "Resource": [
                "*"
            ],
            "Action": [
                "xray:BatchGetTraces",
                "xray:GetTraceGraph",
                "xray:GetServiceGraph",
                "xray:GetTraceSummaries"
            ],
            "Effect": "Allow",
            "Sid": "erwefeer"
        }

**Comment by srprash** [comment]
Hi @neetika123, I would be happy to help you.
A couple of things I would like you to verify. First, once the lambda function is deployed, is the checkbox saying `Active tracing` under AWS X-Ray enabled?
Second, when you run your lambda function, do you see a trace id something like `XRAY TraceId: 1-xxxxxxxx-xxxxxxxxxx	SegmentId: 0c111a1111111111	Sampled: true` in the lambda logs?

I would also like you to change the serverless.yml to be as shown below, and try deploying the lambda function again.
```
tracing:
   lambda: true
```
See [here](https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/) for reference.

**Comment by srprash** [comment]
Hi @neetika123 ,
I am closing this issue for now due to inactivity. Please feel free to reopen if you still encounter the problem.

Thanks!
