### ISSUE TITLE
How to configure x-ray in NET core correctly?

### ISSUE THREAD

**Issue by lethienhoang** [aws/aws-xray-sdk-dotnet#111]
I did a research x-ray to apply to my project. But I have read document on AWS

Example of document is "new HttpClient(new HttpClientXRayTracingHandler(new HttpClientHandler())"

but in NET core we use DI so we doesn't using new HttpClient. That is httpclientfactory createclient

In my statup

```
AWSSDKHandler.RegisterXRayForAllServices();
services.AddHttpClient(namedHttpClient.Name, (serviceProvider, config) => {
....
.ConfigurePrimaryHttpMessageHandler(() =>
                {
                    var handler = new HttpClientHandler();
                    new HttpClientXRayTracingHandler(handler);
                    return handler;
                });
})
```
Json:

```
{
  "version": 2,
  "rules": [
    {
      "description": "Player moves.",
      "host": "*",
      "http_method": "*",
      "url_path": "/api/*",
      "fixed_target": 0,
      "rate": 0.05
    }
  ],
  "default": {
    "fixed_target": 1,
    "rate": 0.1
  }
}
```
In program

```
var config = new ConfigurationBuilder()
                        .AddJsonFile("appsettings.json", optional: false)
                        .Build();

            var recorder = new AWSXRayRecorderBuilder().WithSamplingStrategy(new LocalizedSamplingStrategy(@"C:folder\SamplingRules.json")).Build();
            AWSXRayRecorder.InitializeInstance(config, recorder);
```
In service, using httpClientFacTory to call other api. We are using microservices in system.

`var contentService = _httpClientFactory.CreateClient("");`

`var response = await contentService.SendAsync(request);`
The restult after testing is there is no infor of x-ray in request and response. I dont know it has working yet? Please help me I dont know about this sdk. How to configuration them in correct? Thanks

**Comment by bhautikpip** [comment]
Hi @lethienhoang,

Thanks for reaching out. For initial configuration if you follow .net core section in this link (https://github.com/aws/aws-xray-sdk-dotnet) then I think you should be good. Moreover, one important thing to keep in mind is that if you want to trace outgoing HTTP requests then you should follow steps mentioned in this link (https://github.com/aws/aws-xray-sdk-dotnet#trace-out-going-http-requests-net-and-net-core--nuget). It looks like you are making async downstream HTTP request. I think you should use GetAsyncResponseTraced() to trace your call. Let me know if you have any further questions. Hope this helps!

**Comment by lethienhoang** [comment]
Hi @bhautikpip  I don't see GetAsyncReosponeTraced method in HttpRequestMessage

**Comment by bhautikpip** [comment]
Hi @lethienhoang,

what I mean is you can use GetAsyncReosponeTraced method to trace async http calls.

**Comment by srprash** [comment]
> I did a research x-ray to apply to my project. But I have read document on AWS
> 
> Example of document is "new HttpClient(new HttpClientXRayTracingHandler(new HttpClientHandler())"
> 
> but in NET core we use DI so we doesn't using new HttpClient. That is httpclientfactory createclient
> 
> In my statup
> 
> ```
> AWSSDKHandler.RegisterXRayForAllServices();
> services.AddHttpClient(namedHttpClient.Name, (serviceProvider, config) => {
> ....
> .ConfigurePrimaryHttpMessageHandler(() =>
>                 {
>                     var handler = new HttpClientHandler();
>                     new HttpClientXRayTracingHandler(handler);
>                     return handler;
>                 });
> })
> ```
> 
> Json:
> 
> ```
> {
>   "version": 2,
>   "rules": [
>     {
>       "description": "Player moves.",
>       "host": "*",
>       "http_method": "*",
>       "url_path": "/api/*",
>       "fixed_target": 0,
>       "rate": 0.05
>     }
>   ],
>   "default": {
>     "fixed_target": 1,
>     "rate": 0.1
>   }
> }
> ```
> 
> In program
> 
> ```
> var config = new ConfigurationBuilder()
>                         .AddJsonFile("appsettings.json", optional: false)
>                         .Build();
> 
>             var recorder = new AWSXRayRecorderBuilder().WithSamplingStrategy(new LocalizedSamplingStrategy(@"C:folder\SamplingRules.json")).Build();
>             AWSXRayRecorder.InitializeInstance(config, recorder);
> ```
> 
> In service, using httpClientFacTory to call other api. We are using microservices in system.
> 
> `var contentService = _httpClientFactory.CreateClient("");`
> 
> `var response = await contentService.SendAsync(request);`
> The restult after testing is there is no infor of x-ray in request and response. I dont know it has working yet? Please help me I dont know about this sdk. How to configuration them in correct? Thanks

Hi @lethienhoang 
You need to return an instance of HttpClientXRayTracingHandler in your ConfigurePrimaryHttpMessageHandler method.

example:
```csharp
services.AddHttpClient("foo")
                .ConfigurePrimaryHttpMessageHandler(() =>
                {
                    return new HttpClientXRayTracingHandler(new HttpClientHandler());
                });
```

One question I have is that are unable to see the subsegment for outgoing http requests from your application or you are not seeing any traces at all?

**Comment by srprash** [comment]
Hi @lethienhoang 
Closing this issue die to inactivity. In case your question still remains unanswered, feel free to reopen and we will help you out.
