### ISSUE TITLE
I set "DisableXRayTracing": "true" in appsettings.json It will disable tracing of httpclient right?

### ISSUE THREAD

**Issue by lethienhoang** [aws/aws-xray-sdk-dotnet#116]
In project, At local we don't want to trace httprequest from httpclientFactory. That just only for production.

So I set "DisableXRayTracing": "true"  . Is that correct? I try it at 1 service then I still having amazon-id:..., parentId : ...

**Comment by bhautikpip** [comment]
Hi @lethienhoang ,

DisableXRayTracing option will disable end to end tracing of your application but if you want to disable tracing only http calls then simply do not use the tracing handler provided by X-Ray to trace http calls and you will not be able to trace http downstream calls. Let me know if you need more clarification.

**Comment by awssandra** [comment]
Closing as inactive.
