### ISSUE TITLE
Custom Start/End Time Resolution

### ISSUE THREAD

**Issue by matthewdouglas** [aws/aws-xray-sdk-dotnet#118]
I am using XRay to trace an ASP.NET Web API application, using the included `AWSXRayASPNET` handler.

I have noticed that every request trace has a beginning timestamp that starts exactly on the second. This is adding extra duration time to the traces as seen here:
![image](https://user-images.githubusercontent.com/38992547/72263476-ee995d80-35e6-11ea-8c2e-b4b067d35486.png)

The start of the segment should instead be much closer to the start of the first subsegment.

The `AWSXRayASPNET` handler gets the starting timestamp from `HttpContext.Timestamp` which should have higher than 1-second resolution. The issue is that `Entity.SetStartTime(DateTime timestamp)` will perform a Floor operation on the starting timestamp:

```csharp
private static decimal GetUnixSeconds(DateTime utcNow)
{
    return decimal.Floor(utcNow.ToUnixTimeSeconds());
}
```

This does not appear to happen with `Entity.SetStartTime(decimal timestamp)` or in turn, `Entity.SetStartTimeToNow()`.

It would seem that there shouldn't be any reason to floor the timestamp. Happy to submit a PR if needed.

**Comment by srprash** [comment]
Hi @matthewdouglas 
Thanks for the deep dive and uncovering the issue. I'm not really sure why we floor the timestamp in `SetStartTime(DateTime timestamp)` and not in the other methods. Feel free to open a PR.

**Comment by matthewdouglas** [comment]
Hi @srprash 
Is there anything else you need from me to before PR #119 can be merged?
