### ISSUE TITLE
.NET Core Console App "Entity doesn't exist in AsyncLocal"

### ISSUE THREAD

**Issue by samkbit** [aws/aws-xray-sdk-dotnet#121]
Various issues have been reporting this error **Entity doesn't exist in AsyncLocal** and my scenario is a bit different. My application is NOT AspNetCore app, it is a NetCore Console app project where I am simply calling an API and I want to trace it with XRay. I am getting that error. 

The simplest possible code to replicate the issue is below.

    Configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: false)
                .AddJsonFile($"appsettings.development.json", optional: true, reloadOnChange: false)
                .AddJsonFile($"appsettings.test.json", optional: true, reloadOnChange: false)
                .AddJsonFile($"appsettings.production.json", optional: true, reloadOnChange: false)
                .AddEnvironmentVariables()
                .Build();

    Environment.SetEnvironmentVariable(
          "AWS_XRAY_DAEMON_ADDRESS",
          "172.16.215.205:2000");

    AWSXRayRecorder.InitializeInstance(configuration: Configuration);
    AWSSDKHandler.RegisterXRayForAllServices();

    // per XRAY SDK for .NET documentation, use the delegating handler HttpClientXRayTracingHandler provided by AWS
    // https://github.com/aws/aws-xray-sdk-dotnet#using-systemnethttpclient
    var httpClient = new HttpClient(new HttpClientXRayTracingHandler(new HttpClientHandler()));

    var publicApiUrl = "http://webservices.amazon.com/";

    // Error occurs here
    var response = await httpClient.GetAsync(publicApiUrl);

Error detail

    Amazon.XRay.Recorder.Core.Exceptions.EntityNotAvailableException: Entity doesn't exist in AsyncLocal
    at Entity Amazon.XRay.Recorder.Core.Internal.Context.AsyncLocalContextContainer.GetEntity()
    at void Amazon.XRay.Recorder.Core.AWSXRayRecorder.AddSubsegment(Subsegment subsegment, Nullable<DateTime> timestamp)
    at void Amazon.XRay.Recorder.Core.AWSXRayRecorder.BeginSubsegment(string name, Nullable<DateTime> timestamp)
    at void Amazon.XRay.Recorder.Core.AWSXRayRecorder.BeginSubsegment(string name, Nullable<DateTime> timestamp)
    at void Amazon.XRay.Recorder.Handlers.System.Net.Utils.RequestUtil.ProcessRequest(Uri uri, string method, Action<string> addHeaderAction)
    at async Task<HttpResponseMessage> Amazon.XRay.Recorder.Handlers.System.Net.HttpClientXRayTracingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    at async Task<HttpResponseMessage> System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task<HttpResponseMessage> sendTask, HttpRequestMessage request, CancellationTokenSource cts, bool disposeCts)

I read somewhere here that with ASPNETCORE, the main **segment** is already created and that every trace call is adding a **subsegment** and everything works. 

What lines of code can I add above in the simplest possible manner so that the call goes thru?

**Comment by matthewdouglas** [comment]
@samkbit You'll want to call `BeginSegment()` and `EndSegment()` as per the example here: https://github.com/aws/aws-xray-sdk-dotnet#creating-custom-segmentsubsegment-net-and-net-core

**Comment by srprash** [comment]
@samkbit The recorder automatically creates a `Segment` only for instrumented ASP .Net applications. For you console app, you'll have to manually begin and end a segment.

**Comment by samkbit** [comment]
Ah ok this worked thank you both @matthewdouglas and @srprash. However, a related question below.

If I have a message handler class (hooked to some message bus) in a console app project and if the handler method on that class gets invoked **concurrently**, will there be concurrency issues when **trace IDs** are generated by `BeginSegment()` statements?

**Comment by srprash** [comment]
If your console app is handling each invocation in a multi-threaded manner, the `BeginSegment()` should create a segment and put it in the `AsyncLocal` of each thread. You can set the trace id while creating a segment. See [`BeginSegment`](https://github.com/aws/aws-xray-sdk-dotnet/blob/40d3c0e924eb8e41c1b28fab073cfd36b4c986f3/sdk/src/Core/AWSXRayRecorderImpl.cs#L151) method.
