### ISSUE TITLE
OpenTelemetry support

### ISSUE THREAD

**Issue by albertocorrales** [aws/aws-xray-sdk-dotnet#126]
The OpenTelemetry specification describes the cross-language requirements and expectations for all OpenTelemetry implementations (https://opentelemetry.io/about/). 

Right now if we want to use OpenTelemetry to have our dotnet core applications more platform agnostic, we don't have the possibility of using X-Ray. 

Regarding dotnet core implementation (https://github.com/open-telemetry/opentelemetry-dotnet), it is about to be released as beta and other vendors already provide exporters for it, so it would be great to see X-Ray in that list.

Thanks,

Alberto.

**Comment by bhautikpip** [comment]
Hi @albertocorrales,

Thanks for opening this issue. I will add this item to out backlog!

**Comment by bravecobra** [comment]
I'm really looking forward to this as OpenTelemetry is now implemented by default in .NET 5.0 (https://devblogs.microsoft.com/dotnet/announcing-net-5-0/). 
If it works for java, how hard can it be to add support for .NET?

**Comment by lupengamzn** [comment]
Hi @bravecobra ,

We've been working with OpenTelemetry to add support for X-Ray in .NET. Please stay tuned and come back later to check.

**Comment by lupengamzn** [comment]
Hey @albertocorrales @bravecobra , 

AWS Distro for Opentelemetry .NET SDK is released today, please take reference to:

Blog:
- https://aws.amazon.com/blogs/opensource/aws-distro-for-opentelemetry-adds-net-tracing-support/

User guide: 

- https://aws-otel.github.io/docs/getting-started/dotnet-sdk

Nugets:

- [OpenTelemetry.Contrib.Extensions.AWSXRay](https://www.nuget.org/packages/OpenTelemetry.Contrib.Extensions.AWSXRay/)
- [OpenTelemetry.Contrib.Instrumentation.AWS](https://www.nuget.org/packages/OpenTelemetry.Contrib.Instrumentation.AWS/)

Upstream repo: 

- https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src

Please feel free to provide feedback and contribute

Cheers

**Comment by albertocorrales** [comment]
This is awesome news, I'm looking forward to using the new SDK for OpenTelemetry. Great job guys!!!
