### ISSUE TITLE
Thread Safety with AWSXRayRecorder.Instance

### ISSUE THREAD

**Issue by kinan-ellevation** [aws/aws-xray-sdk-dotnet#140]
Given that [AWSXRayRecorder.Instance](https://docs.aws.amazon.com/xray-sdk-for-dotnet/latest/reference/html/P_Amazon_XRay_Recorder_Core_AWSXRayRecorder_Instance.htm) is a singleton, is using AWSXRayRecorder.Instance thread safe? If not, how can we modify the [sample xray subsegment](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-dotnet-subsegments.html) code to guarantee thread safety?

```
AWSXRayRecorder.Instance.BeginSubsegment("custom method");
try
{
  AWSXRayRecorder.Instance.AddMetadata(someData);
  DoWork();
}
catch (Exception e)
{
  AWSXRayRecorder.Instance.AddException(e);
}
finally
{
  AWSXRayRecorder.Instance.EndSubsegment();
}
```

**Comment by srprash** [comment]
Hi @kinan-ellevation 
The X-Ray SDK creates only a single instance of AWSXRayRecorder for the application process. The SDK uses AsyncLocal storage for maintaining the trace context for each thread independently. Any Segment/Subsegment created within a thread is stored in the AsyncLocal of that thread only and therefore using the recorder instance is thread safe.

Are you running into any thread related issue while using the SDK?

**Comment by kinan-ellevation** [comment]
Thanks a ton @srprash. I am not running into any issues with thread safety using the SDK. One of my colleagues left a comment on one PR and asked me whether the SDK was thread safe. Alas, I couldn't find this information anywhere. Thank you for providing the answer.

**Comment by kinan-ellevation** [comment]
My recommendation is to update the documentation to make it clear that the SDK is thread safe so that future generations will find this information easily.

**Comment by srprash** [comment]
We do have a small section on [multi-threaded execution](https://github.com/aws/aws-xray-sdk-dotnet/tree/master#multithreaded-execution-net-and-net-core--nuget) which mentions the CallContext and AsyncLocal usage. But I agree we can do a better documentation. Thanks!
