### ISSUE TITLE
Your documentation doesn't mention using `Amazon.XRay.Recorder.Handlers.EntityFramework;` for EF MySQL

### ISSUE THREAD

**Issue by paulito-bandito** [aws/aws-xray-sdk-dotnet#144]
Hi guys, 

Could be mistaken. Your documentation (the README.md for this github project) doesn't seem to indicate that we should add the

- `Amazon.XRay.Recorder.Handlers.EntityFramework;`

Package in order to add this to my MySQL connection for Entity Framework. 

- `.AddXRayInterceptor()`

Had to find it via this links:

- https://net-immersionday.workshop.aws/6-using-x-ray-in-dotnet-application/8-entity-framework-tracing.html

**Comment by lupengamzn** [comment]
Hi @paulito-bandito ,

Thanks for the feedback

Yes, you need to install `AWSXRayRecorder.Handlers.EntityFramework` package inside your application to call `AddXRayInterceptor()`. 

Sorry for the confusion and we will add this instruction step in the `README.md` file soon.

**Comment by paulito-bandito** [comment]
Thanks very much, and great project btw. Keep up the great work.

**Comment by lupengamzn** [comment]
Hey @paulito-bandito , this PR has been merged. [@145](https://github.com/aws/aws-xray-sdk-dotnet/pull/145)

**Comment by paulito-bandito** [comment]
great!
