### ISSUE TITLE
Please release a version of AWSXRayRecorder.Handlers.System.Net which targets AWSSDK.XRay 3.5.*

### ISSUE THREAD

**Issue by ShaneGH** [aws/aws-xray-sdk-dotnet#150]
We are currently unable to use this package as it targets an old version of AWSSDK.Core through an old version of AWSSDK.XRay

At build time:
project\Shared.Http\Shared.Http.csproj : error NU1608: Detected package version outside of dependency constraint: AWSSDK.XRay 3.3.3 requires AWSSDK.Core (>= 3.3.25.1 && < 3.4.0) but version AWSSDK.Core 3.5.1.23 was resolved.

**Comment by lupengamzn** [comment]
Closing this issue as it will be addressed in the next release
