### ISSUE TITLE
Please release a version of AWSXRayRecorder.Handlers.System.Net which targets AWSSDK.XRay 3.5.*

### ISSUE THREAD

**Issue by ShaneGH** [aws/aws-xray-sdk-dotnet#153]
The current version of AWSXRayRecorder.Handlers.System.Net prevents users from using the latest versions of other Aws Sdks because of its reference to an old version of AWSSDK.Core

**Comment by lupengamzn** [comment]
Closing this issue as it will be addressed in the next release
