### ISSUE TITLE
Exception - An item with the same key has already been added

### ISSUE THREAD

**Issue by sdolier** [aws/aws-xray-sdk-dotnet#156]
Hi,

This is a copy of an issue I have logged over on the .net auto instrumentation repo.

https://github.com/aws/aws-xray-dotnet-agent/issues/19

However, I think the fix is to do with the SDK.

We are receiving the following exception intermittently.

```
Exception information: 
    Exception type: ArgumentException 
    Exception message: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2..ctor(IDictionary`2 dictionary, IEqualityComparer`1 comparer)
   at Amazon.XRay.Recorder.Core.AWSXRayRecorderImpl.AddRuleName(Segment newSegment, SamplingResponse sampleResponse)
   at Amazon.XRay.Recorder.Core.AWSXRayRecorderImpl.PopulateNewSegmentAttributes(Segment newSegment, SamplingResponse sampleResponse)
   at Amazon.XRay.Recorder.Core.AWSXRayRecorderImpl.BeginSegment(String name, String traceId, String parentId, SamplingResponse samplingResponse, Nullable`1 timestamp)
   at Amazon.XRay.Recorder.AutoInstrumentation.Utils.AspNetRequestUtil.ProcessHTTPRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

We receive this issue occasionally on application start. Once this issue occurs every request to the application then throws this exception. Causing the website to go down. I assume it could also happen on an application recycle.

It is hard to reproduce. I cannot reliably reproduce the issue, but it happens frequently. In our case when deploying an ElasticBeanstalk application version.

Our application makes lots of threaded http requests on startup. I believe this could be the cause.

I have been trying out this as a fix: https://github.com/sdolier/aws-xray-sdk-dotnet/commit/34167e89218d0357bc2bfa6f5821473664a46ab0

It is only a partial solution as there are other areas of the library that need to be updated to a ConcurrentDictionary.

I feel there should be global try/catch logic in this library, like in logging libraries (nlog, log4net). A monitoring/logging library should not be able to break a parent application.

**Comment by lupengamzn** [comment]
Hey @sdolier ,

Please see https://github.com/aws/aws-xray-dotnet-agent/issues/19

**Comment by sdolier** [comment]
Hi,

I have had this fix in our environment for a few weeks now and have not experienced any more of the same exceptions.

**Comment by lupengamzn** [comment]
Hey @sdolier ,

Sorry for the late response, will take a look at the PR later today

**Comment by lupengamzn** [comment]
Hey @sdolier ,

I was working on this issue recently and it turned out it's hard to reproduce on my side. Do you mind providing a sample example that is similar to your use case?

Thanks a lot

**Comment by sdolier** [comment]
Hi @lupengamzn,

I am not able to reliably reproduce the issue.

The exception occurs intermittently during deployment (Elastic Beanstalk). My assumption is that during application start there are many threaded/concurrent outbound http requests causing the issue.

Before this fix I would get the exception every ~1 in 5 deployments. I haven't seen one since converting the context to a concurrent dictionary.

**Comment by lupengamzn** [comment]
@sdolier , so we decided to keep this issue open for further discussion and I believe you're not bothered by this issue any more as you're using the library that you've fixed. Once this issue was reproduced on our side, we'll fix it in the next release. Sorry for the inconvenience.

**Comment by lupengamzn** [comment]
@sdolier , thanks for the patience.

The `XRay` dictionary belongs to `AWSXRayRecorder` instance, which can be accessed by segments of multiple threads within the same application. It's safe to use regular `Dictionary` if multiple segments will only be reading values from it, but will not be thread-safe if segments are trying to [modify](https://github.com/aws/aws-xray-sdk-dotnet/blob/8461c354d783da96a052015ff111f31a91b131d0/sdk/src/Core/AWSXRayRecorderImpl.cs#L379-L390) it concurrently. Hence, the `XRay` dictionary in `RuntimeContext` needs to be switched to `ConcurrentDictionary` for the sake of thread safety.

Thanks for pointing this out and your PR has been approved and merged!
