### ISSUE TITLE
What registers HttpClientXRayTracingHandler?

### ISSUE THREAD

**Issue by chazt3n** [aws/aws-xray-sdk-dotnet#163]
from [the docs related to httpclientFactory](https://github.com/aws/aws-xray-sdk-dotnet#using-systemnethttphttpclientfactory-net-core-21-and-above)

this code blows up with: 

```cs
services.AddHttpClient<IFooClient, FooClient>()
        .AddHttpMessageHandler<HttpClientXRayTracingHandler>();
```
>No service for type Amazon.XRay.Recorder.Handlers.System.Net.HttpClientXRayTracingHandler has been registered.

How do I ensure that that is provided?

**Comment by Kralizek** [comment]
Simply add
```csharp
services.AddTransient<HttpClientXRayTracingHandler>();
```

**Comment by chazt3n** [comment]
Thank you. 

If I use the autoinstrument agent, will I get XRay functionality without having to pepper my code (which has many entry points other than web requests) with manual xray segments?

**Comment by lupengamzn** [comment]
Hey @chazt3n ,

If you apply auto instrumentation agent, you don't have to modify your code base and your application will be automatically traced.
