### ISSUE TITLE
Adding Annotations and Metadata to parent most trace from within AWS Lambda

### ISSUE THREAD

**Issue by jstallm** [aws/aws-xray-sdk-dotnet#165]
While I can see within the documentation how to create a custom SubSegment within a lambda application, I dont see anywhere how to add an annotation or metadata to the top-most segment.

Unfortunately trying to invoke .AddAnnotation(..)  shown below simply does not result in the data being saved
```
            AWSXRayRecorder recorder = new AWSXRayRecorder();
            recorder.AddAnnotation("AnnotationName1", "1234");
```
After trying the above, no annotations are shown in the AWS console (shown below)
![image](https://user-images.githubusercontent.com/6054668/101393255-a678ce80-387b-11eb-824a-690e45ca29d1.png)

I suspect there to be some probability that this is not supported in the SDK?
Within my AWS C# Lambda project, I have initialized xray as follows
```
AWSXRayRecorder.InitializeInstance(root);
AWSSDKHandler.RegisterXRayForAllServices();
```

Can you please confirm if creating annotations and metadata is supported for lambdas? And if so update the documentation to showcase this feature capability and/or its limitations?

Here is my CSPROJ info

```
	<PropertyGroup>
		<TargetFramework>netcoreapp3.1</TargetFramework>
		<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
		<AWSProjectType>Lambda</AWSProjectType>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>
```

And here are my nuget packages
```
		<PackageReference Include="AWSSDK.XRay" Version="3.5.2.16" />
		<PackageReference Include="AWSXRayRecorder.Core" Version="2.9.0" />
		<PackageReference Include="AWSXRayRecorder.Handlers.AspNetCore" Version="2.7.1" />
		<PackageReference Include="AWSXRayRecorder.Handlers.AwsSdk" Version="2.8.1" />
```

I understand that lambdas have segments automatically created for the lambda invocation, but what I am looking for is adding annotations/metadata to that segment, and its associated custom subsegments. 

Update 1: I see now that I can only add Annotations to a custom subsegment. Is it not possible to add an annotation to the parent most lambda auto-created segment? 

It should be noted somewhere if adding annotations/metadata is not supported to parent most segment within lambdas to avoid confusion. 

I feel like when I invoke 
```
            AWSXRayRecorder recorder = new AWSXRayRecorder();
            recorder.AddAnnotation("AnnotationName1", "1234");
```
Data is not streaming to the XRay backend , even though no runtime exceptions.

Update 2: Odd, I feel like I am supposed to be getting runtime exceptions when I invoke methods on the new AWSXRayRecorder instance, but for some reason am not getting runtime exceptions. Is there a setting in the SDK itself that controls whether or not runtime exceptions are thrown when operations are performed on the parent-most segment?

**Comment by lupengamzn** [comment]
Hey @jstallm ,

The `segment` created by Lambda runtime is immutable, thus you'll not be able to add annotations/metadata to it. Lambda only allows adding annotations/metadata to the `subsegment` created by your function code. Please take a look at Lambda's [doc](https://docs.aws.amazon.com/xray/latest/devguide/xray-services-lambda.html)(Scroll down to the bottom of page)

**Comment by lupengamzn** [comment]
@jstallm , for your second question, you may have multiple `AWSXRayRecorder` instances in your application and they'll all have access to the current trace context so you'll not see the runtime exception. However, a more preferred and suggested way to initialize `AWSXRayRecorder` would be:

```
var recorder = AWSXRayRecorder.Instance;
```
Above method will guarantee that there will be only one `AWSXRayRecorder` instance created.
