### ISSUE TITLE
Naming of SNS segment

### ISSUE THREAD

**Issue by johankvint** [aws/aws-xray-sdk-dotnet#166]
Not sure how to formulate this, but here we go.

So when using SNS client in dotnet with XRay, the subsegment/document is named `SimpleNotificationService` where as when I use SNS client in node with XRay the subsegment/document is named `SNS`.

This causes them to be shown in different ways in XRay console where the `SNS` naming seems to be "correctly" interpreted as a SNS node.

I have two services, one in dotnet and one in node that both publish to the same SNS topic but they show up as separate nodes in the XRay console.

Is the dotnet sns client naming the segment wrong or is there something I need to setup?

## dotnet
<img width="199" alt="Screenshot 2020-12-15 at 09 32 07" src="https://user-images.githubusercontent.com/6551731/102205559-a5731d00-3ecb-11eb-9d47-c68d5e65c297.png">

### Code
startup.cs
```
public IServiceProvider ConfigureServices(IServiceCollection services)
{
    AWSSDKHandler.RegisterXRayForAllServices();
    ...
}
```

service.cs
```
using var snsClient = new AmazonSimpleNotificationServiceClient();
...
var publishResponse = await snsClient.PublishAsync(publishRequest);
...
```

### dotnet subsegment
```
{
    "id": "07ae62c6aff00b02",
    "name": "SimpleNotificationService",
    "start_time": 1608020987.101566,
    "end_time": 1608020987.605851,
    "http": {
        "response": {
            "status": 200,
            "content_length": 294
        }
    },
    "aws": {
        "topic_arn": "arn:aws:sns:eu-west-1:*******",
        "region": "eu-west-1",
        "request_id": "1de5ef77-5263-51da-a03b-b72524580124",
        "operation": "Publish"
    },
    "namespace": "aws"
}
```

### dotnet document
```
{
    "Document": {
        "id": "02532c1b2e6ab3d0",
        "name": "SimpleNotificationService",
        "start_time": 1608020987.101566,
        "trace_id": "1-5fd873fa-3b8589bd20c663146e34bc7a",
        "end_time": 1608020987.605851,
        "parent_id": "07ae62c6aff00b02",
        "inferred": true,
        "http": {
            "response": {
                "status": 200,
                "content_length": 294
            }
        },
        "aws": {
            "topic_arn": "arn:aws:sns:eu-west-1:*******",
            "region": "eu-west-1",
            "request_id": "1de5ef77-5263-51da-a03b-b72524580124",
            "operation": "Publish"
        },
        "origin": "AWS::SimpleNotificationService"
    },
    "Id": "02532c1b2e6ab3d0"
}
```

## Node
<img width="203" alt="Screenshot 2020-12-15 at 09 31 54" src="https://user-images.githubusercontent.com/6551731/102205696-d5babb80-3ecb-11eb-8b57-790c064d3ae7.png">

### Code
```
const sns = AWSXRay.captureAWSClient(new SNS());
sns.publish(params, (err, data) => {
    ..
});
```

### Lambda subsegment
```
{
    "id": "7a4a467dd895a4ac",
    "name": "SNS",
    "start_time": 1608021002.778,
    "end_time": 1608021003.139,
    "http": {
        "response": {
            "status": 200
        }
    },
    "aws": {
        "retries": 0,
        "topic_arn": "arn:aws:sns:eu-west-1:*******",
        "region": "eu-west-1",
        "operation": "Publish",
        "request_id": "01140e4e-1444-56b4-9616-561c620f6e73",
        "resource_names": [
            "arn:aws:sns:eu-west-1:*******"
        ]
    },
    "namespace": "aws"
}
```

### Lambda document
```
{
    "Document": {
        "id": "066fd5a534027fb8",
        "name": "SNS",
        "start_time": 1608021002.778,
        "trace_id": "1-5fd873fb-4ca832a8ae7d33ac4dba66e8",
        "end_time": 1608021003.139,
        "parent_id": "7a4a467dd895a4ac",
        "inferred": true,
        "http": {
            "response": {
                "status": 200
            }
        },
        "aws": {
            "retries": 0,
            "topic_arn": "arn:aws:sns:eu-west-1:*******",
            "region": "eu-west-1",
            "operation": "Publish",
            "request_id": "01140e4e-1444-56b4-9616-561c620f6e73",
            "resource_names": [
                "arn:aws:sns:eu-west-1:*******"
            ]
        },
        "origin": "AWS::SNS"
    },
    "Id": "066fd5a534027fb8"
}
```

**Comment by lupengamzn** [comment]
Hey @johankvint ,

Thanks for pointing this out

X-Ray SDK will adopt the AWS SDK request name as the subsegment [name](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Handlers/AwsSdk/Internal/XRayPipelineHandler.cs#L322), and seems like there is a naming difference between .NET and other languages of AWS SDK. I've tested JS, Java as well as Python SDK and they're all adopting `SNS` as the subsegment name for sns request. I agree that XRay .NET SDK should follow the same behavior as other languages. I will sync with AWS .NET SDK team and get back to you soon.

**Comment by johankvint** [comment]
@lupengamzn I was suspecting that was the case. I guess more service will give the wrong name then as well.
Maybe you could use the `ServiceId` from meta data instead?
https://github.com/aws/aws-sdk-net/blob/37bc48277594d96f20122fad9c5e136730c27f26/sdk/src/Services/SimpleNotificationService/Generated/Internal/AmazonSimpleNotificationServiceMetadata.cs#L38

That seems to have the correct value for all services

**Comment by lupengamzn** [comment]
Hey @johankvint , we've decided to add a checker when creating SNS subsegment so that the subsegment name to SNS service would be recorded as `SNS` instead of `SimpleNotificationService`. This fix will be included in the next release.

**Comment by lupengamzn** [comment]
Hey, 

AWS X-Ray .NET SDK v2.10.0 has been released, which should have solved this issue.

Closing this thread
