### ISSUE TITLE
Missing AWSXRayRecorder.Handlers.System.Net;

### ISSUE THREAD

**Issue by Basel78** [aws/aws-xray-sdk-dotnet#17]
Hi,
I am using XRay API mentioned in this Repo, for logging Lambda Function that i built on ASPNetCore 2.0 and used httpclient to call another endpoint to get JSON result, so I wanted to follow the instruction to log the request as mentioned in **Trace out-going HTTP requests (.NET and .NET Core)** and noticed the following:

1. using AWSXRayRecorder.Handlers.System.Net; -- Is Missing although I have added all packages exactly as mentioned in the beginning of article, " _Search AWSXRayRecorder* to see various middlewares available.... etc._"
2.  HttpClientTracingHandler in : the code line below is Missing, do I need to write this function?
`var httpClient = new HttpClient(new HttpClientTracingHandler(new HttpClientHandler()));`

It's good to mention that I was able to use Tracing Asynchronous method and Creating Segment and Subsegment to the LambdaFunction.

Thanks
Basel

**Comment by Basel78** [comment]
One more Question,
How can we run & Pass Test Project that comes with LambdaFunction when using AWSXRayRecorder object created in the functionHandler , without having the error:
`Message: Amazon.XRay.Recorder.Core.Exceptions.EntityNotAvailableException : Entity doesn't exist in AsyncLocal`

**Comment by nedjs** [comment]
@Basel78 Take a look at https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/test/UnitTests/TraceContextTests.cs and do something similar. You probably want to something like 

```
var origin = new Subsegment("test");
TraceContext.SetEntity(origin);
```

**Comment by yogiraj07** [comment]
Hi @Basel78 ,

Thank you for reaching out to us.

1. `AWSXRayRecorder.Handlers.System.Net` is a nuget package that needs to be install to use the functionality. Please clean the project, and it might solve the import issue.

2. We have merged pull request for `HttpClientTracingHandler` and its still yet to be released in the form of nuget package. We would soon make a release, which includes this support.

3. A subsegment created inside Lambda function, expects segment to be already available in the `TraceContext`. When you deploy Lambda function, Lambda creates segment for you. In case of test project, which I assume, you run it locally, please create a segment before the unit test starts and close it after the unit test is completed. This will solve your issue.

Please let me know if you have any questions.

Thanks,
Yogi

**Comment by yogiraj07** [comment]
Hi @Basel78 ,

We have release version `2.2.0-beta` which includes support for `HttpClient`.
Changelog : https://github.com/aws/aws-xray-sdk-dotnet/blob/master/CHANGELOG.md
I am closing this issue. Please feel free to reopen if you have any questions.

Best,
Yogi

**Comment by Basel78** [comment]
Hi @yogiraj07 ,
Thank you for the update, I have upgraded XRay Packages to the latest 2.2.0 Beta and followed the code changes updated in ReadMe which make my unit test project working fine and test passed :)

Now when I deployed the code on AWS lambda and ran the configure test event with the payload, I got error as below
```One or more errors occurred. (Cannot override Facade Segment. New segment not created.): AggregateException
 at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
 at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

 at Amazon.XRay.Recorder.Core.AWSXRayRecorder.BeginSegment(String name, String traceId, String parentId, SampleDecision sampleDecision)
 at MSMACA.CompareAgreement.<CompareHandler>d__12.MoveNext() in C:\XXX\YY-Lambda\XXXXXXX-YYYYY\XXXXX\Function.cs:line 72
```


so the error message says : `Cannot override Facade Segment. New segment not created.):` and the code line mentioned in the error is like that
` AWSXRayRecorder.Instance.BeginSegment("CompareHandler");`

what surprise me more in the error stack above is how the lambda function recognize the location of the files in my local machine, and was able to mention exactly the Full path of my folder locally!!
**C:\XXX\YY-Lambda\XXXXXXX-YYYYY\XXXXX\Function.cs:line 72**
Do you have any explanation to that?

Thanks,
Basel

**Comment by normj** [comment]
By default even in Release mode msbuild will generate pdb files which will contain the file paths at build time. If you want to disable that in your csproj file set `DebugType` equal to `None`

```xml
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>

    <DebugType>None</DebugType>

  </PropertyGroup>
```

**Comment by yogiraj07** [comment]
Hi @Basel78,

You cannot create `segment` inside Lambda function. A `segment` is generated on your behalf by  Lambda which is known as `FacadeSegment`. Hence you see the error.

Initially, I thought you intend to run unit test on a local environment (not Lambda). So I recommended to manually create `segment` around the unit test and not the Lambda function.

Please let me know if you have questions and thanks @normj for the insights.

Best,
Yogi
