### ISSUE TITLE
Poor documentation around AspNetCore integration requirements

### ISSUE THREAD

**Issue by julealgon** [aws/aws-xray-sdk-dotnet#170]
The [documentation for integrating XRay in a .Net Core application](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-dotnet-messagehandler.html#xray-sdk-dotnet-messagehandler-startupcs) currently mentions several other middlewares in the code samples without providing an actual explanation about why they are included.

The docs mention having to add `UseExceptionHandler` as well as `UseStaticFiles` to startup when integrating with XRay, but the only mention of these other standard middlewares is in an ordering issue:
> Always call UseXRay after UseExceptionHandler to record exceptions. If you use other middleware, enable it after you call UseXRay.

I believe the documentation should be vastly improved here:
- Are these other middlewares required?
- Why are each of them required specifically?
- Can their requirement be lifted if one doesn't want to add them?

The text above also implies that `UseXRay` should happen as early as possible in the pipeline, but doesn't exactly mention where. Please consider adding this documentation to the extension method itself, so that people are aware of the details while programming. See a nice example from Serilog's request logging middleware extension:
- ![image](https://user-images.githubusercontent.com/461579/103415693-179d6000-4b62-11eb-86c2-f41227cfee7b.png)

Notice the last sentence in the summary:
> Add this in `Startup.cs` before any handlers whose activities should be logged.

Now compare to XRay's documentation:
> Adds `Amazon.XRay.Recorder.Handlers.AspNetCore.Internal.AWSXRayMiddleware` to the applicaion's request pipeline.

Notice I'm not specifically asking "why" in this issue ([I'm doing that in StackOverflow instead](https://stackoverflow.com/questions/65521990/why-does-aws-xray-require-useexceptionhandler-and-usestaticfiles-in-aspnetco)). This is exclusively about updating the documentation to present more details about the integration itself. If you want to answer the actual questions, please consider doing that in SO so that the community benefits as well.

**Comment by lupengamzn** [comment]
Hey @julealgon ,

Thanks for pointing this out and we'll be updating the user guide and API doc soon.

**Comment by julealgon** [comment]
Thanks @lupengamzn !

Could you please bump/close this issue once the docs are updated?

**Comment by lupengamzn** [comment]
Hey @julealgon ,

The [developer doc](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-dotnet-messagehandler.html#xray-sdk-dotnet-messagehandler-startupcs) has been updated.

Closing this issue as it's addressed

**Comment by julealgon** [comment]
Thanks for the update @lupengamzn . I checked the new docs and they solve all the issues I raised: they are a lot more precise and clear now.
