### ISSUE TITLE
Method not found BeginSubsegment

### ISSUE THREAD

**Issue by erwan-joly** [aws/aws-xray-sdk-dotnet#177]
For some reasons my build pipeline is not able to use AWSXRayRecorder.Handlers.AspNetCore 2.7.1
everything works fine with AWSXRayRecorder.Handlers.AspNetCore 2.5.2 but when I do bump to 2.7.1 it start to fail on build pipeline (locally it works fine)

xunit on linux throws:

`System.MissingMethodException : Method not found: 'Void Amazon.XRay.Recorder.Core.AWSXRayRecorderImpl.BeginSubsegment(System.String)'.`

I'm getting the error on both dotnet core 3.1 and dotnet 5

Any idea what could be the origin of this issue ?

**Comment by awssandra** [comment]
Hi erwan-joly,

Looks like this is a generic issue, with NuGet projects and possibly old DLLs hanging around: https://stackoverflow.com/questions/8058832/system-missingmethodexception-method-not-found

Can you do a sanity check to see if anything from 2.5.2 is hiding?

**Comment by erwan-joly** [comment]
Yes that was the reason :)
