### ISSUE TITLE
Please release code which updates dependencies to AWSSDK.Core 3.5.*

### ISSUE THREAD

**Issue by ShaneGH** [aws/aws-xray-sdk-dotnet#178]
The code change/fix for the following issues has not been released to nuget 

https://github.com/aws/aws-xray-sdk-dotnet/issues/151
https://github.com/aws/aws-xray-sdk-dotnet/issues/152
https://github.com/aws/aws-xray-sdk-dotnet/issues/153

![image](https://user-images.githubusercontent.com/3628842/107251521-56111f00-6a2c-11eb-9778-9ca8f8206dea.png)

**Comment by lupengamzn** [comment]
Hey @ShaneGH ,

Sorry for the late reply!

Previously we didn't have the bandwidth for the new release and now we're in the process of doing it, the new release will be out hopefully in a week or two.

**Comment by ShaneGH** [comment]
Thanks for that. I'll keep an eye on this issue

**Comment by lupengamzn** [comment]
Hey @ShaneGH ,

Thanks for the patience, the X-Ray .NET SDK v2.10.0 has been released. 

https://www.nuget.org/packages?q=awsxrayrecorder

**Comment by btecu** [comment]
@lupengamzn `2.10.0` is still referencing `AWSSDK.Core` `3.3.x` instead of `3.5.x`.

**Comment by lupengamzn** [comment]
Hey @btecu ,

The previous .NET SDK referenced to `AWSSDK.XRay` `v3.3.3`, which will cause the build time [error/warning](https://github.com/aws/aws-xray-sdk-dotnet/issues/151) when `AWSSDK.Core` dependency in your application is newer than `v3.4.0`. For .NET SDK `v2.10.0`, we removed `AWSSDK.XRay` dependency and you should be able to install and use the latest AWS SDK in your application. Do you still have the same issue mentioned in #151 using the latest X-Ray .NET SDK?

**Comment by ShaneGH** [comment]
@lupengamzn  @btecu 

Thanks!

**Comment by btecu** [comment]
@lupengamzn I still have to include a reference to `AWSSDK.Core Version="3.5.x"` because the application is using a library that uses the newer `S3` (with `AWSSDK.Core`) and it causes an issue because the XRay Recorder references the `AWSSDK.Core` `3.3.x`.

**Comment by lupengamzn** [comment]
@btecu When both dependencies have the same sub-dependency at the same distance, it should be resolved. See [Cousin dependencies](https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution#cousin-dependencies).

Can you post what warning/error you're getting when you installed X-Ray .NET SDK?
