### ISSUE TITLE
Inject TraceID in to log messages

### ISSUE THREAD

**Issue by bruceharrison1984** [aws/aws-xray-sdk-dotnet#196]
The Java SDK exposes AWS-XRAY-TRACE-ID in the MDC to allow for easily adding TraceID to log messages, which allows ServiceLens to marry up X-Ray segments and log messages. It would be great to have this same behavior within the C# library, or at least an easy to access value for adding traceId to log messages in a similar fashion.

From the Java X-Ray SDK:
`
To expose the current fully qualified trace ID to your log statements, you can inject the ID into the mapped diagnostic context (MDC). Using the SegmentListener interface, methods are called from the X-Ray recorder during segment lifecycle events. When a segment or subsegment begins, the qualified trace ID is injected into the MDC with the key AWS-XRAY-TRACE-ID. When that segment ends, the key is removed from the MDC. This exposes the trace ID to the logging library in use. When a subsegment ends, its parent ID is injected into the MDC.
`

https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html#xray-sdk-java-configuration-logging

**Comment by srprash** [comment]
Hi @bruceharrison1984 
Thanks for opening this feature request. We have added this item in a backlog. However, due to all our efforts currently directed towards developing X-Ray support for OpenTelemetry .Net, it may not be prioritized soon. 
If you'd like to contribute the implementation for this feature, I'll be happy to review. :) 

Thanks!

**Comment by DanielLaberge** [comment]
@srprash In the meantime, is there any way to get application logs to show up in XRay Traces?

**Comment by bruceharrison1984** [comment]
@DanielLaberge I'm curious to know this as well. 

@srprash 
Is the current TraceId available in a statically accessible location so it can be added to log messages? And if so, what format does it need to appear in the logs for ServiceLens to take advantage of it?

**Comment by srprash** [comment]
@DanielLaberge @bruceharrison1984 
The trace id to log correlation involves 2 pieces to work:
1. A resource plugin (EC2 or ECS) on the X-Ray SDK to record the log-group id on the trace data. https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/deploy_servicelens_CloudWatch_agent_logintegration.html
2. Trace-id and segment-id injection to CloudWatch logs in a specific format. https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html#xray-sdk-java-configuration-logging

For the X-Ray .Net SDK, I believe it is still possible to do the 2nd part by fetching the trace-id and segment-id of the current segment and passing it into logger. However, the current resource plugins are missing the [logic to get the CW log group ARN](https://github.com/aws/aws-xray-sdk-java/blob/5143932f0da7d921c07fc8149d14c3f767cb09ee/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/plugins/EC2Plugin.java#L103-L156) to enable ServiceLens to do the actual correlation.

**Comment by bruceharrison1984** [comment]
@srprash I appreciate you closing the loop on this 👍

**Comment by luizfds** [comment]
I know it's an old thread, but I will comment anyway, as it can help others.

After seeing this [GitHub issue and comment](https://github.com/aws/aws-xray-sdk-python/issues/188#issuecomment-728222591) in the aws-xray-sdk-python I decided to try the same on .NET SDK and got the same result.

Here is what I did.

![image](https://github.com/aws/aws-xray-sdk-dotnet/assets/83678534/1095b999-ae5a-4474-82a9-283491094acc)
