### ISSUE TITLE
Make internal AWSXRayRecorder constructors public

### ISSUE THREAD

**Issue by bittercoder** [aws/aws-xray-sdk-dotnet#20]
Currently there is a overload of `AWSXRayRecorder.InitializeInstance` which takes 2 parameters

* configuration: IConfiguration
* recorder: AWSXRayRecorder

This seems well suited to supporting custom configurations (such as supplying your own implementation or wrapper around the UDP segment emitter).

But unfortunately the useful constructor overloads of AWSXRayRecorder in this instance are marked internal so you can't inject your own implementation of a segment emitter.

To work around this I need to do something like:

```
var constructors = typeof(AWSXRayRecorder).GetConstructors(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
var constructor = constructors.First(x => {
	var parameters = x.GetParameters();
	return parameters.Length == 2 && parameters[0].ParameterType == typeof(ISegmentEmitter) && parameters[1].ParameterType == typeof(XRayOptions);
});
var xrayOptions = Configuration.GetXRayOptions();
var emitter = appOptions.LogAwsXRaySegments ? (ISegmentEmitter)new LoggingUdpSegmentEmitter() : new UdpSegmentEmitter();
var recorder = (AWSXRayRecorder)constructor.Invoke(new object[] {emitter, xrayOptions});
AWSXRayRecorder.InitializeInstance(Configuration, recorder);
```

Which is more friction then I would like - it would be great if some of those internal constructors could be made public.

**Comment by yogiraj07** [comment]
Hi @bittercoder ,

Thank you for raising this issue. We plan to make the SDK as modular as possible and happy to  review the pull request.

Thanks,
Yogi

**Comment by bittercoder** [comment]
The use case for the custom emitter in my case initially was for diagnosing some issues e.g. figuring out if the emitter was actually emitting metrics and confirming it was emitting to the correct address.

We also introduced a logging emitter to log the payload being emitted, this was useful during local development/testing where you might not have the daemon running, but you would to confirm your custom segments were being published correctly.

**Comment by yogiraj07** [comment]
Hi @bittercoder ,

Thank you for letting us know your use case.

I am reviewing your pull request.

Bets,
Yogi

**Comment by richardgavel** [comment]
I would think instead of making the internal constructors public, a better option, given the existing usage of the builder pattern (https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/AwsXrayRecorderBuilder.cs), that you add a WithSegmentEmitter method on it.

**Comment by yogiraj07** [comment]
Hi @richardgavel ,
I agree with your suggestion and would make necessary changes to builder class. Thank you for your feedback.

**Comment by yogiraj07** [comment]
We have made `2.2.1-beta release` : https://github.com/aws/aws-xray-sdk-dotnet/blob/master/CHANGELOG.md , that includes this support.

Thanks,
Yogi
