### ISSUE TITLE
LitJson GUID type support

### ISSUE THREAD

**Issue by MadSciencist** [aws/aws-xray-sdk-dotnet#202]
Hi.

Looks like the LitJson used for serialization does not properly handle GUID types. 

Minimum code to reproduce it:
```csharp
        public class AnythingWithGuid
        {
            public Guid Id { get; set; }
        }

        [TestMethod]
        public void SerializeObjectContainingGuid_ThrowsError()
        {
            var obj = new AnythingWithGuid();
            JsonMapper.ToJson(obj);
            Assert.IsNotNull(obj);
        }
```
The error: ThirdParty.LitJson.JsonException: Max allowed object depth reached while trying to export from type System.Guid.

Is there any workaround for it? Is such behavior documented?
Might be related: https://github.com/aws/aws-xray-sdk-dotnet/issues/109

Thanks,
Mateusz

**Comment by srprash** [comment]
The [fix](https://github.com/aws/aws-xray-sdk-dotnet/pull/203) has been released in v2.11.0. Please let us know if this issue still persists.
