### ISSUE TITLE
question | missing subsegments 

### ISSUE THREAD

**Issue by kvattikuti** [aws/aws-xray-sdk-dotnet#205]
So I have been experimenting with X-Ray with API Gateway + Lambda that uses SQS, SNS and Kinesis service clients. Works great, shows all the segments logged by service clients. I added a subsegment in FunctionHandler method, and that also is traced and shown in the X-Ray traces. It was great. 

However, we use Mediatr framework (and Lamar for DI) that for our request handling/ processing. I added subsegments in those handler classes but I don't see those subsegment traces being logged by X-Ray. I am at loss on how to debug this issue. I just enabled Console logging in the hope of finding something useful in the log stream. I use AWSXRayRecorder.Instance to record subsegments. Any suggestions or thoughts that will help me figure this out will be appreciated. Thanks.

**Comment by kvattikuti** [comment]
Correct, in the Lambda, I am adding a subsegment which shows up correctly in the traces just to see if it will show up and it does!

`AWSXRayRecorder.Instance.BeginSubsegment("FunctionHandler"); `

You can see "FunctionHandler" in the screen shot.
<img width="1555" alt="Screen Shot 2021-06-09 at 5 08 39 PM" src="https://user-images.githubusercontent.com/1224094/121430059-9d111180-c945-11eb-839a-4a0aef1ffbe3.png">

FunctionHandler will invoke Medaitr to process the request which does a bunch of things like sending message to SNS/SQS/Kinesis and update Postgres database. I added few subsegments just like above code snippet (ofcours with a matching begin/addexception/end in finally etc. I don't see any of those custom subsegments. A fragment of code 👍 
```
private async Task<IEnumerable<MessageWithPayload>> DeliverToDb(
            IDictionary<string, MessageWithPayload> messageWithPayloads,
            IEntityDefinition entityDefinition)
        {
            IList<string> successUpsertIds;
            try
            {
                _commandContext.XrayBeginSubsegment("DeliverToDb");
                // update db
                var deliveryDatabase = _commandDeliveryDatabaseFactory.GetDeliveryDatabase(entityDefinition);
                var listOfPayloadAndETags = messageWithPayloads.Values.Select(messageWithPayload => new PayloadEtagPair
                    {Payload = messageWithPayload.Payload, ETag = messageWithPayload.ETag}).ToList();
                var allUpsertIds = messageWithPayloads.Keys;
                successUpsertIds = await deliveryDatabase.UpsertAsync(listOfPayloadAndETags, 500, false);

                // upsert 
                allUpsertIds.Except(successUpsertIds).ForEach(SetDatabaseEtagCheckFailed);

            }
            catch (Exception e)
            {
                _commandContext.XrayAddException(e);
                throw e;
            }
            finally
            {
                _commandContext.XrayEndSubsegment();
            }
            // return messagepayloads that were successful
            return successUpsertIds.Select(id => messageWithPayloads[id]);
        }
```

_commandContext.Xray***** will inturn use AWSXRayRecorder.Instance to add subsegments.
Happy to provide more info or code snippets.

**Comment by kvattikuti** [comment]
And I call Mediatr like this in the scope of the FunctionHandler:
```

private async Task<APIGatewayProxyResponse> ProcessRequestUsingRequestProcessor(
            ApiGatewayProxyRequestWrapper requestWrapper,
            IEntityDefinition entityDefinition,
            INestedContainer nestedContainer,
            ILogger logger,
            string correlationId)
        {
            var apiGatewayProxyDaaSRequestAdapter =
                nestedContainer.GetInstance<ApiGatewayProxyRequestProcessorAdapter>();

            logger.Debug("Initiating Request to RequestProcessor");
            try
            {
                var daaSRequest = apiGatewayProxyDaaSRequestAdapter.CreateDaaSRequest(requestWrapper,
                    entityDefinition is IReadonlySqlViewEntity);
                var mediator = nestedContainer.GetInstance<IMediator>();
                var daaSResponse = await mediator.Send(daaSRequest);
                logger.Debug("Request processed and Response returned from RequestProcessor");
                return apiGatewayProxyDaaSRequestAdapter.CreateApiGatewayProxyResponse(requestWrapper,
                    (IDaaSResponse) daaSResponse, requestWrapper.IsBulkIngest, requestWrapper.IsWaitForSuccess);
            }
            catch (InvalidPayloadException invalidPayloadException)
            {
                return ApiGatewayProxyRequestProcessorAdapter.CreateApiGatewayDefaultProxyResponse(
                    HttpStatusCode.BadRequest, invalidPayloadException.Message);
            }
            catch (Exception exception)
            {
                logger.Error(Util.ExceptionToString(exception));
                return ApiGatewayProxyRequestProcessorAdapter.CreateApiGatewayDefaultProxyResponse(HttpStatusCode
                    .InternalServerError);
            }
        }

```

**Comment by kvattikuti** [comment]
So are you saying if a Lambda function handler calls another sync/ async method of different class and I cannot begin a new subsegment in that method? I probably don't understand the internals of the implementation, why would that make a difference, isn't it the same thread though?

**Comment by lupengamzn** [comment]
@kvattikuti , Thanks for providing the code snippets. So the Lambda handler will invoke the Medaitr to process downstream business and later will update the Postgres database, and you're seeing the traces of Medaitr block, but not seeing the Postgres block. If this is the case, seems like there is something wrong creating/ending the `DeliverToDb` subsegment. Can you check the Lambda log to see if there is any error log regarding `DeliverToDb` subsegment? If there isn't any, can you try printing out the trace id of `DeliverToDb` subsegment in your code and compare with the trace id of Lambda to see if it's the same?

**Comment by kvattikuti** [comment]
Sorry, it is just me being a giant idiot. I was running the wrong test so obviously not seeing what I am expecting. Thanks for the help and super quick response.
