### ISSUE TITLE
Skip OPTIONS requests

### ISSUE THREAD

**Issue by AlissonRS** [aws/aws-xray-sdk-dotnet#207]
Hello!

I noticed in my app most traces are "OPTIONS" requests sent by browsers.

Is there a way we can skip these requests?

![image](https://user-images.githubusercontent.com/4753901/126239512-db790b83-f564-4db3-a50e-6fc93fab278b.png)

**Comment by willarmiros** [comment]
Hi @AlissonRS,

You can choose not to trace requests with method `options` by creating a sampling rule that matches all requests with HTTP method "OPTIONS" and has a sampling rate of 0%. This should effectively prevent any such segments from being sent to X-Ray. See more [in our sampling docs](https://docs.aws.amazon.com/xray/latest/devguide/xray-console-sampling.html#xray-console-sampling-options), and please reopen this if you have further questions.

**Comment by AlissonRS** [comment]
Yeah seems like this is not working.

I added a `sampling-rules.json` in my .NET Core project, set it to "Copy Always" to ensure it goes with compiled app:

```
{
  "version": 2,
  "rules": [
    {
      "description": "Skip OPTIONS requests.",
      "host": "*",
      "http_method": "OPTIONS",
      "url_path": "*",
      "fixed_target": 0,
      "rate": 0
    }
  ]
}
```

And added it in my `appsettings.json` and even `appsettings.Development.json`:

 ```
 "XRay": {
    "SamplingRuleManifest": "sampling-rules.json"
  },
```

But when I debug, the `SamplingRuleManifest` is null:

![image](https://user-images.githubusercontent.com/4753901/127081001-a64e7f95-c1d9-4747-a355-4ffa3053f4da.png)

On top of that, there are other scenarios I'd like to skip a trace that can't be configured in these sampling rule files.

OPTIONS request was just one case, but I have other cases. I was expecting some way we can programmatically ignore traces for a given request.

Thanks!!!

**Comment by AlissonRS** [comment]
@willarmiros I just created a new issue with my specific requirement, and provided what I tried so far.
