### ISSUE TITLE
How to trace postgresql query 

### ISSUE THREAD

**Issue by harikantkumar** [aws/aws-xray-sdk-dotnet#211]
I am using https://www.npgsql.org/doc/api/Npgsql.NpgsqlConnection.html and https://martendb.io/getting_started/
to connect C# .net core app with postgresql. Please help me how we can enable sql tracing

**Comment by willarmiros** [comment]
Please see: https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-dotnet-sqlqueries.html

**Comment by harikantkumar** [comment]
@willarmiros 

Thank you for your resposne, I am not using entity framwork
My application  is using  https://www.npgsql.org/doc/api/Npgsql.NpgsqlConnection.html and https://martendb.io/getting_started/
