### ISSUE TITLE
LitJson does not properly handle models that contain recursive public properties. Examples: Guid, DateTimeOffset

### ISSUE THREAD

**Issue by kdprince** [aws/aws-xray-sdk-dotnet#212]
```
 public class ModelWithSelfReferenceProp
  {
      public ModelWithSelfReferenceProp()
      {
          RightNow = DateTime.Now;
      }
      public DateTimeOffset RightNow { get; }
  }

  [Fact]
  public void TestShouldNotThrowError()
  {
      var model = new ModelWithSelfReferenceProp();
      
      JsonMapper.ToJson(model);
      Assert.NotNull(model);
  }
```
Max allowed object depth reached while trying to export from type System.DateTimeOffset

Infinite recursion here: https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/ThirdParty/LitJson/JsonMapper.cs#L828

This is most likely same issue as https://github.com/aws/aws-xray-sdk-dotnet/issues/202

**Comment by srprash** [comment]
[Fix](https://github.com/aws/aws-xray-sdk-dotnet/pull/203) for serializing GUID has been released in v2.11.0.

**Comment by ehampusklarin** [comment]
OK it's fixed for Guid, but what about others such as DateTimeOffset, DateOnly, TimeOnly?

**Comment by jusbuc2k** [comment]
Having this problem with booleans as well.
