### ISSUE TITLE
X-Ray Cannot Find a Handler of Type `EndpointResolver`

### ISSUE THREAD

**Issue by chrisoverzero** [aws/aws-xray-sdk-dotnet#267]
Since the release of AWSSDK service client libraries which includes AWSSDK.DynamoDBv2 version 3.7.100, Amazon.XRay.Recorder.Handlers.AwsSdk can no longer customize service clients due to being unable to find a handler for the type `EndpointResolver`. The service clients fail to be constructed, as a consequence.

Here is the stack trace for attempting to resolve an instance of `IAmazonDynamoDB`:

```json
{
  "errorType": "InvalidOperationException",
  "errorMessage": "Cannot find a handler of type EndpointResolver",
  "stackTrace": [
    "at Amazon.Runtime.Internal.RuntimePipeline.AddHandlerAfter[T](IPipelineHandler handler)",
    "at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineCustomizer.Customize(Type serviceClientType, RuntimePipeline pipeline) in /_/sdk/src/Handlers/AwsSdk/Internal/XRayPipelineHandler.cs:line 748",
    "at Amazon.Runtime.Internal.RuntimePipelineCustomizerRegistry.ApplyCustomizations(Type type, RuntimePipeline pipeline)",
    "at Amazon.Runtime.AmazonServiceClient.BuildRuntimePipeline()",
    "at Amazon.Runtime.AmazonServiceClient..ctor(AWSCredentials credentials, ClientConfig config)",
    "at Amazon.DynamoDBv2.AmazonDynamoDBClient..ctor(AWSCredentials credentials, AmazonDynamoDBConfig clientConfig)"
  ]
}
```

**Comment by normj** [comment]
X-Ray team this was a change that went out with the AWS .NET SDK yesterday. Sorry about the miss here updating X-Ray. I'll send over a PR to address the change shortly.

**Comment by chrisoverzero** [comment]
Ah, I wasn't quite certain where to file the report. Apologies if this was off the mark.

**Comment by normj** [comment]
@chrisoverzero The code change has to go here so this was the right spot.

**Comment by chrisoverzero** [comment]
That's great, thanks so much.

Lookin' forward to Amazon.XRay.Recorder.Handlers.AwsSdk 2.9.2.

**Comment by roelvandenbrand** [comment]
Testing with the current versions (core 3.7.100.7 & xray 2.11.1) and it does not work.

**Comment by srprash** [comment]
Hi @roelvandenbrand 
We are yet to release this fix. We will be prioritizing it soon. Please stay tuned.

**Comment by roelvandenbrand** [comment]
> Hi @roelvandenbrand We are yet to release this fix. We will be prioritizing it soon. Please stay tuned.

The release seems to be hanging on issue #102 or can you release without that change?

**Comment by Ahmad-anility** [comment]
> > Hi @roelvandenbrand We are yet to release this fix. We will be prioritizing it soon. Please stay tuned.
> 
> The release seems to be hanging on issue #102 or can you release without that change?

I think it is included in the recent release https://github.com/aws/aws-xray-sdk-dotnet/blob/master/CHANGELOG.md#fixed

**Comment by roelvandenbrand** [comment]
Nice! We'll start testing it  :-D

**Comment by srprash** [comment]
The fix has been released in v2.12.0.
I'm closing this issue, but feel free to reopen if the issue still persists. Thanks for being patient.

**Comment by emiliano-tortorelli-zocdoc** [comment]
I'm using the following versions of the packages and still seeing this issue when trying to do
`new AmazonTextractClient(credentials, RegionEndpoint.USEast1);` 

```
    <PackageReference Include="AWSSDK.Core" Version="3.7.103.10" />
    <PackageReference Include="AWSSDK.Textract" Version="3.7.104.25" />
    <PackageReference Include="AWSXRayRecorder.Core" Version="2.13.0" />
    <PackageReference Include="AWSXRayRecorder.Handlers.AwsSdk" Version="2.11.0" />
```
Should this be working for AWSSDK.Textract?

**Comment by AndrewC999** [comment]
I am seeing this same "X-Ray Cannot Find a Handler of Type EndpointResolver" issue with AWSDSK.Xray with the DynamoDB client with the following versions:

    <PackageReference Include="AWSSDK.Core" Version="3.7.103.24" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.101.33" />
    <PackageReference Include="AWSSDK.XRay" Version="3.7.102.43" />

this causes the following line of code that has been working for years to evaluate to 'null':

AmazonDynamoDBClient dbClient = new AmazonDynamoDBClient();

 Shouldn't this be working?

**Comment by FotG** [comment]
I am also still hitting this on the latest versions of the AWS SDKs, specifically, SQS, S3 and SWF. I see this marked as "Pending Release". Is there a timeline for a release?

**Comment by srprash** [comment]
@FotG This fix has been released. I have removed the "pending release" tag.

>I am also still hitting this on the latest versions of the AWS SDKs, specifically, SQS, S3 and SWF

Can you ensure that you are resolving to the latest versions of the packages in your application? 
https://github.com/aws/aws-xray-sdk-dotnet/issues/284#issuecomment-1412909785

**Comment by FotG** [comment]
I solved it, another unrelated profiling package causing this to happen.

**Comment by alexanderjshall** [comment]
Just for visibility in case anyone else comes across this issue, some of the `OpenTelemetry` packages suffer from the same issue - requires similar upgrades to latest versions
- `OpenTelemetry.Contrib.Extensions.AWSXRay` (definitely works from 1.2.0)
- `OpenTelemetry.Contrib.Instrumentation.AWS` (definitely works from 1.0.2)
