### ISSUE TITLE
Best approach for local testing of handlers

### ISSUE THREAD

**Issue by Kralizek** [aws/aws-xray-sdk-dotnet#27]
Hi!

I'm working on a XRay handler for WCF (both on service and client side) (https://github.com/Kralizek/xray-wcf)

I've got the basics going and now it's about polishing. Currently I've been deploying my sample project to am EC2 instance but it gets annoying after a while. And it makes difficult to debug.

Is there any better approach to allow local development/testing?

**Comment by Kralizek** [comment]
Hi @yogiraj07

The need for a local setup is only to speed up the development and testing of this handler.

There is no need for a local setup when developing a WCF service/client consuming this package.

I will try installing the Daemon on my local machine (or maybe even a container ad hoc)

Thanks for your comment

**Comment by yogiraj07** [comment]
Hi @Kralizek ,
I am closing this issue. Please feel free to reopen if you have any questions.

Best,
Yogi
