### ISSUE TITLE
Race condition - intermittent exceptions "Operations that change non-concurrent collections must have exclusive access"

### ISSUE THREAD

**Issue by udlose** [aws/aws-xray-sdk-dotnet#282]
Hi,

I was experiencing the same race condition as explained in #67 and have a small project that has been able to repro the issue (of course intermittently since it's a race condition).  I have posted the sample solution here: https://github.com/udlose/AWSXRayRaceCondition

- .NET Core 7.0
- AWSXRayRecorder 2.13.0

```
AWSXRayRaceConditionTests.TelemetryRecorderTests.Trace CallsActionAndRecords WhenTracingIsEnabled
   Source: TelemetryRecorderTests.cs line 82
   Duration: 1 ms

  Message: 
System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.

  Stack Trace: 
Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
Dictionary`2.set_Item(TKey key, TValue value)
JsonMapper.RegisterExporter[T](ExporterFunc`1 exporter) line 922
JsonSegmentMarshaller.ctor() line 48
UdpSegmentEmitter.ctor() line 45
AWSXRayRecorder.ctor() line 47
TelemetryRecorderTests.ctor() line 25
RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```

**Comment by udlose** [comment]
It appears the root cause of the race is in `LitJson` which appears to be used by `AWSXRayRecorder`.  I've opened a PR with `LitJson` project.  You would obviously need to consume the latest version once they accept the PR and release the fix.

- `LitJson` Issue: https://github.com/LitJSON/litjson/pull/143
- `LitJson` PR: https://github.com/LitJSON/litjson/pull/142

**Comment by jj22ee** [comment]
Hi @udlose,

It looks like your PR to `LitJson` hasn't gotten any traction. We've faced a similar issue with this dependency before and that is why we have the source code of `LitJson` directly in this repository (`aws-xray-sdk-dotnet/sdk/src/Core/ThirdParty/LitJson/JsonMapper.cs`).

Can you make your PR changes to `LitJson` to `aws-xray-sdk-dotnet/sdk/src/Core/ThirdParty/LitJson/` as well, so you do not need to further wait for the maintainers of `LitJson` to approve your PR? Also can you apply the changes without the formatting changes to make the review easier?

**Comment by Compufreak345** [comment]
Hi @udlose ,
we are facing the same issue here, so I would like to second the ask from @jj22ee . 

You would help us a ton if you could do that :)

Thanks & best regards,
Christoph

**Comment by udlose** [comment]
I've updated my PR to LitJson (https://github.com/LitJSON/litjson/pull/142) and will re-create a duplicate PR against this repo tonight.

**Comment by udlose** [comment]
@Compufreak345 , @jj22ee PR submitted. I noticed there was some code in the latest JsonMapper.cs that wasn't included here so I left that in the PR.  Feel free to remove if desired.

**Comment by jj22ee** [comment]
Thanks for submitting the PR. I see that most of the PR Checks are failing due to a `ThirdParty.LitJson.JsonException`. The Unit Tests are failing due to a recursive (infinite?) loop in the the [WriteValue()](https://github.com/aws/aws-xray-sdk-dotnet/blob/3a5cf9906609322648dedf8c92e5e0f81ac6e3f3/sdk/src/Core/ThirdParty/LitJson/JsonMapper.cs#L710-L712) method. Added a comment in the PR.

**Comment by jj22ee** [comment]
Thanks @udlose. We cannot directly depend on `LitJson` as there is some custom code in our own copy of the `LitJSON`, so we will need to cherry-pick your specific change into our repository. I've updated your PR to do so, and restored some accidentally deleted code.

**Comment by jj22ee** [comment]
PR is merged. Once we release the next version, I can close this issue.

**Comment by jj22ee** [comment]
Closing issue since PR is merged, the next release of XRay Dotnet SDK will include this bugfix.
