### ISSUE TITLE
"X-Ray Cannot Find a Handler of Type EndpointResolver" error, DynamoDB client does not instantiate

### ISSUE THREAD

**Issue by AndrewC999** [aws/aws-xray-sdk-dotnet#284]
Similar to this existing issue: #267 

I am seeing this same "X-Ray Cannot Find a Handler of Type EndpointResolver" issue with AWSDSK.Xray with the DynamoDB client after upgrading to the following versions, which I believe are the latest:

    <PackageReference Include="AWSSDK.Core" Version="3.7.103.24" />
    <PackageReference Include="AWSSDK.Lambda" Version="3.7.104.3" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.101.33" />
    <PackageReference Include="AWSSDK.XRay" Version="3.7.102.43" />

This causes the following line of code that has been working for years to evaluate to 'null':

`AmazonDynamoDBClient dbClient = new AmazonDynamoDBClient();`

![EndpointResolver error](https://user-images.githubusercontent.com/124001858/215807520-acbc9322-e596-4915-83e9-cefb06af6287.png)

**Comment by amid0** [comment]
Having the same issue right now but with AmazonCloudWatchClient

**Comment by srprash** [comment]
Hi @AndrewC999 @amid0 
Sorry that this issue hasn't been resolved by the fix we did. I am looking into this right now.
In the meantime, can you confirm that everything works fine for the X-Ray SDK v2.13.0 and the AWSSDK version prior to 3.7.100?

**Comment by srprash** [comment]
We are not using the `EndpointResolver` anymore anywhere (after [this change](https://github.com/aws/aws-xray-sdk-dotnet/pull/268/files)) in the X-Ray SDK, so I wonder why is this still an error.

**Comment by normj** [comment]
I would recommend looking in the build output's `*.deps.json` file to see if something unexpecting is forcing an older version of `AWSXRayRecorder.Handlers.AwsSdk`.

**Comment by AndrewC999** [comment]
Thanks for looking into this, @srprash.

Before updating to those packages we were not having any issues. This is every package we were using (other than an internal library] **before** the upgrade that broke our code:

Main project:

   <PackageReference Include="Amazon.Lambda.S3Events" Version="2.0.1" />
    <PackageReference Include="AWSSDK.Core" Version="3.7.12.4" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.3.52" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.9.20" />
    <PackageReference Include="AWSSDK.SimpleEmailV2" Version="3.7.1.103" />
    <PackageReference Include="AWSSDK.SQS" Version="3.7.2.73" />
    <PackageReference Include="AWSSDK.StepFunctions" Version="3.7.0.176" />
    <PackageReference Include="AWSSDK.Lambda" Version="3.7.13.18" />
    <PackageReference Include="AWSSDK.SecretsManager.Caching" Version="1.0.4" />
    <PackageReference Include="AWSSDK.SecretsManager" Version="3.7.2.60" />
    <PackageReference Include="AWSSDK.XRay" Version="3.7.0.176" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.20.0" />
    <PackageReference Include="AWSSDK.Glue" Version="3.7.19.1" />


Unit test project:

   <PackageReference Include="Amazon.Lambda.Core" Version="2.1.0" />
    <PackageReference Include="Amazon.Lambda.TestUtilities" Version="2.0.0" />
    <PackageReference Include="AWSSDK.Core" Version="3.7.12.4" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.3.52" />
    <PackageReference Include="AWSSDK.SQS" Version="3.7.2.73" />
    <PackageReference Include="AWSSDK.XRay" Version="3.7.0.176" />
    <PackageReference Include="coverlet.msbuild" Version="3.1.2"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.2.0" />
    <PackageReference Include="moq" Version="4.18.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5" />
    <PackageReference Include="AWSSDK.Glue" Version="3.7.19.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.20.0" />

This is what's used in our internal library which is referenced in the above main project:

    <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="1.2.0" />
    <PackageReference Include="Amazon.Lambda.Core" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.DynamoDBEvents" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.6.0" />
    <PackageReference Include="Amazon.Lambda.SQSEvents" Version="1.1.0" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.5.4.5" />
    <PackageReference Include="AWSXRayRecorder.Core" Version="2.11.1" />
    <PackageReference Include="AWSXRayRecorder.Handlers.AwsSdk" Version="2.9.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.1.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.0.601" />
    <PackageReference Include="AWSSDK.SQS" Version="3.5.0.46" />
    <PackageReference Include="AWSSDK.Core" Version="3.5.1.46" />
    <PackageReference Include="AWSSDK.XRay" Version="3.5.4.11" />
    <PackageReference Include="AWSSDK.SecretsManager" Version="3.5.0"/>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />

**Comment by AndrewC999** [comment]
@normj looking at .deps.json for the debug build on my local, for the code with the above-mentioned package versions, every mention of AWSXRayRecorder.Handlers.AwsSdk refers to this version:

`"AWSXRayRecorder.Handlers.AwsSdk/2.9.1": `

I will try in the next couple days to do the above checks in the branch that has the problematic updated packages.

**Comment by normj** [comment]
@AndrewC999 if you can't change the internal library you can update your `main` app to take an explicit reference on `AWSXRayRecorder.Handlers.AwsSdk` for version 2.11.0 that will override the .NET packaging to make sure 2.11.0 is used.

**Comment by AndrewC999** [comment]
@normj I'll look into the feasibility of upgrading the internal library. Not sure, since it's used across dozens of projects. If it can't be done, I'll try the other option. Hopefully next week.

**Comment by normj** [comment]
Just so you know the fix that is in version 2.11.0 is compatible for the latest version of the SDK as well as older versions before the `EndpointResolver` got moved around triggering the issue.

**Comment by AndrewC999** [comment]
@normj thanks for your input, it does seem that explicitly referencing AWSXRayRecorder.Handlers.AwsSdk v2.11.0 prevents the exception from occurring. @srprash  I need to do a bit more testing to confirm, I'll report back, but so far it seems the issue is indeed not present in the current XRay libraries.

**Comment by AndrewC999** [comment]
Thanks all, this issue looks to be resolved with the explicit package reference. I am closing the issue for now since it does not seem to be related to the latest versions of the packages at all.
