### ISSUE TITLE
Outgoing HTTP request tracing

### ISSUE THREAD

**Issue by aidansteele** [aws/aws-xray-sdk-dotnet#3]
Hiya,

It would be good if the outgoing HTTP tracing was extended to also include HTTP requests issued through `System.Net.Http.HttpClient`. This is just anecdotal, but it seems there is an industry-wide shift towards this new API.

Ideally, the SDK might provide a `DelegatingHandler` subclass that we can inject into the HTTP client for a most-invisible installation of the SDK across our code base. Developers are reluctant to change how they interact with the HttpClient (e.g. no `SendAsyncTraced()`)

Thoughts?

**Comment by yogiraj07** [comment]
Hi @aidansteele,

We appreciate your suggestion. We also welcome you to submit a pull request for this feature.

I am currently closing this issue. We would consider this in our future release.

Thanks,
Yogi
