### ISSUE TITLE
Publish Update

### ISSUE THREAD

**Issue by joelhess** [aws/aws-xray-sdk-dotnet#30]
Can you please publish a 2.2.1 update to the nuget packages? I need the changes from https://github.com/aws/aws-xray-sdk-dotnet/pull/22 in order to work with the AWS IOT Sdks. I've confirmed the latest changes address my issue by grabbing/building the latest code, and injecting the updated nuget locally.

**Comment by yogiraj07** [comment]
Hi @joelhess ,
Thank you for the post. We have prioritized this task and post an update at the earliest.

Best,
Yogi

**Comment by yogiraj07** [comment]
Hi @joelhess,
We have made `2.2.1-beta` release. : https://github.com/aws/aws-xray-sdk-dotnet/blob/master/CHANGELOG.md

Thanks,
Yogi
