### ISSUE TITLE
Exception: "cannot add subsegment to a completed segment."

### ISSUE THREAD

**Issue by geraldbauer** [aws/aws-xray-sdk-dotnet#31]
We are receiving an Amazon.XRay.Recorder.Core.Exceptions.EntityNotAvailableException with the message "Cannot add subsegment to a completed segment."

What we are using 
.net core 2.0 MVC 
installed 
- AWSSDK.Core - 3.3.23
- AWSSDK.S3 - 3.3.18
- AWSXRayRecorder - 2.2.0-beta
- AWSXRayRecorder.Core - 2.2.0-beta
- AWSXRayRecorder.Handlers.AwsSdk - 2.2.0-beta

We have a NuGet package with our business logic code. Within our API controller we call our business logic code within a Task. It appears that this error is related to our spinning up a new thread via Task.Run(...) The reason why we say this is when we remove the Task.Run(...) from the code, we no longer receive the AWSXRay exception "cannot add subsegment to a completed segment." 

We really want to use AWSXRay because we see the value in it - we have a UI API that uses AWSXRay as well as some AWS Lambdas. We have to have spin up a thread to run our business logic because it requires time to crunch. (If it didn't take so long, we would be using Lambdas.)

So, what steps/code do we have to do to resolve this exception?

Code snippets:
public class Startup
{
	public void ConfigureServices(IServiceCollection services)
	{
		Amazon.XRay.Recorder.Handlers.AwsSdk.AWSSDKHandler.RegisterXRayForAllServices();
		
		...
		
		services.AddMvc();
	}
	
	public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
	{
		...
		app.UseXRay("Phoenix.Api.Analysis");
		app.UseMvc();
	}
}

[Route("v1/api/analysis")]
public class AnalysisController : Controller
{
	[HttpPost]
	public IActionResult Create([FromBody] AnalysisModel analysisModel)
	{
		try
		{
			...
			var analysisEngineContainer = new AnalysisEngineContainer(...);
			Task.Run(() => analysisEngineContainer.StartAnalyze(...));
		}
		catch (Exception ex)
		{
			...
			return StatusCode(500);
		}
	}
}

Caught exception:
"{\"ClassName\":\"System.AggregateException\",\"Message\":\"One or more errors occurred.\",\"Data\":{},\"InnerException\":{\"ClassName\":\"Amazon.XRay.Recorder.Core.Exceptions.EntityNotAvailableException\",\"Message\":\"Cannot add subsegment to a completed segment.\",\"Data\":{},\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":\"   at Amazon.XRay.Recorder.Core.Internal.Entities.Entity.AddSubsegment(Subsegment subsegment)\\r\\n   at Amazon.XRay.Recorder.Core.AWSXRayRecorder.AddSubsegment(Subsegment subsegment)\\r\\n   at Amazon.XRay.Recorder.Core.AWSXRayRecorder.BeginSubsegment(String name)\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at Amazon.XRay.Recorder.Core.AWSXRayRecorder.BeginSubsegment(String name)\\r\\n   at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineHandler.ProcessBeginRequest(IExecutionContext executionContext)\\r\\n   at Amazon.XRay.Recorder.Handlers.Aws
Sdk.Internal.XRayPipelineHandler.<InvokeAsync>d__27`1.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext() in E:\\\\JenkinsWorkspaces\\\\v3-trebuchet-release\\\\AWSDotNetPublic\\\\sdk\\\\src\\\\Core\\\\Amazon.Runtime\\\\Pipeline\\\\Handlers\\\\ErrorCallbackHandler.cs:line 58\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at Syste
m.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()\",\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":null,\"HResult\":-2146233088,\"Source\":\"AWSXRayRecorder.Core\",\"WatsonBuckets\":null},\"HelpURL\":null,\"StackTraceString\":\"   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\\r\\n   at Phoenix.Business.Analysis.Engine.AnalysisBuilder.AnalysisNotification.SnsAnalysisNotificationService.Notify(Int64 analysisId, Int32 modelId, String message) in C:\\\\TeamCity\\\\buildAgent\\\\work\\\\Phoenix.Business.Analysis.Engine.AnalysisBuilder\\\\1.0.106\\\\AnalysisBuilder\\\\AnalysisNotification\\\\SnsAnalysisNotificationService.cs:line 30\\r\\n   at Phoenix.Business.Analysis.Engine.AnalysisBuilder.SingleAnalysisEngineContainer.Analyze(Int64 analysisId, IEnumerable`1
 analysisEngineInputs, WarehouseInput resultsWarehouseInput, AnalysisRecordingType analysisRecordingType, Nullable`1 parentAnalysisId) in C:\\\\TeamCity\\\\buildAgent\\\\work\\\\Phoenix.Business.Analysis.Engine.AnalysisBuilder\\\\1.0.106\\\\AnalysisBuilder\\\\SingleAnalysisEngineContainer.cs:line 59\\r\\n   at Phoenix.Business.Analysis.Engine.AnalysisBuilder.AnalysisEngineContainer.StartAnalyze(ImpactAnalysis impactAnalysis, ISingleAnalysisEngineContainer singleAnalysisEngineContainer, Int64 analysisId, List`1 analysisEngineInputs, WarehouseInput warehouseInput, List`1 mrioRegionModelIds, AnalysisRecordingType analysisRecordingType) in C:\\\\TeamCity\\\\buildAgent\\\\work\\\\Phoenix.Business.Analysis.Engine.AnalysisBuilder\\\\1.0.106\\\\AnalysisBuilder\\\\AnalysisEngineContainer.cs:line 125\\r\\n   at Phoenix.Api.Analysis.AnalysisApi.Controllers.v1.AnalysisController.<>c__DisplayClass7_1.<Create>b__0() in C:\\\\Projects\\\\Bitbucket\\\\Phoenix\\\\Api\\\\Analysis\\\\AnalysisApi\\\\Controllers\\\\v1\\\\AnalysisC
ontroller.cs:line 230\\r\\n   at System.Threading.Tasks.Task`1.InnerInvoke()\\r\\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\",\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":null,\"HResult\":-2146233088,\"Source\":\"System.Private.CoreLib\",\"WatsonBuckets\":null,\"InnerExceptions\":[{\"ClassName\":\"Amazon.XRay.Recorder.Core.Exceptions.EntityNotAvailableException\",\"Message\":\"Cannot add subsegment to a completed segment.\",\"Data\":{},\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":\"   at Amazon.XRay.Recorder.Core.Internal.Entities.Entity.AddSubsegment(Subsegment subsegment)\\r\\n   at Amazon.XRay.Recorder.Core.AWSXRayRecorder.AddSubsegment(Subsegment subsegment)\\r\\n   at Amazon.XRay.Recorder.Core.AWSXRayRecorder.BeginSubsegment(String name)\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.
Throw()\\r\\n   at Amazon.XRay.Recorder.Core.AWSXRayRecorder.BeginSubsegment(String name)\\r\\n   at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineHandler.ProcessBeginRequest(IExecutionContext executionContext)\\r\\n   at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineHandler.<InvokeAsync>d__27`1.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext() 
in E:\\\\JenkinsWorkspaces\\\\v3-trebuchet-release\\\\AWSDotNetPublic\\\\sdk\\\\src\\\\Core\\\\Amazon.Runtime\\\\Pipeline\\\\Handlers\\\\ErrorCallbackHandler.cs:line 58\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()\",\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":null,\"HResult\":-2146233088,\"Source\":\"AWSXRayRecorder.Core\",\"WatsonBuckets\":null}]}"

**Comment by yogiraj07** [comment]
Hi @geraldbauer ,
Thank you for reporting your use-case.
The reason for the above exception is the `Segment` started as a part of incoming request by the the X-Ray Middleware is closed before the `Subsegment` is started in the `analysisEngineContainer.StartAnalyze(...)`. 

If you want `Subsegment` (created inside the asynchronous job) to be part of existing `Segment` (created by the middleware), you have to `await` you asynchronous `analysisEngineContainer.StartAnalyze(...)` call, so the `Subsegment` gets registered on the `Segment` (present on the main thread) before it closes.

However, if you don't want to use `await`, you need to manually create `Segment` inside `analysisEngineContainer.StartAnalyze(...)`, insert your logic, close the `Segment`. This will make sure  `Segment` is present in the `TraceContext` when a `Subsegment` is created in the asynchronous job. The result of this integration is, you would have 2 separate service graph, one for webapp and another for asynchronous job.

Please let me know if you have any question.

Best,
Yogi

**Comment by geraldbauer** [comment]
Hi Yogi,
Wonderful news and thank you for responding. Kind-a thought that AWS X-Ray was thread specific based upon what I saw. I will follow what is documented in https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-dotnet-subsegments.html. 

This conversion is making me ponder about 1) Parallel.ForEach and 2) recursive calls. Currently we are only doing foreach looping and planning on turning that into a Parallel.ForEach. Within our looping we are recursively calling back into the same looping logic. We anticipate at least one recursive call and hopefully (but not proven) less than 1000 total loops per API call. From this conversation, I am assuming we will need subsegments per Parallel.ForEach thread? (I know I need to test this but time is limited.)

Any concerns here with how AWS X-Ray will behave? I want to have some warm and fuzzies on what is going to happen with AWS X-Ray in 1) recursive looping and 2) recursive parallel looping. In a future sprint, we will make the Parallel.ForEach change and adding subsegements to our code base, but I want to document our steps and concerns first.

Thank you for your time and assistance.

Cheers,
Gerald

**Comment by yogiraj07** [comment]
Hi @geraldbauer ,
We have a test on `Parallel` which would help to get context: https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/test/UnitTests/AWSXRayRecorderTests.cs#L163

When you use `Parallel.ForEach`, current underlying `Segment/Subsegment` gets copied to new logical thread spawned by `Parallel`. `Subsegment` created inside `Parallel.ForEach` would be processed independently in its entirety. 

You would need to add `Subsegment` inside `Parallel.ForEach`. 
Can you please explain more on recursive call?

Is it something like this:

```
Parallel.ForEach(x, (y) => 
                                {
                                   recursiveFunc(); // business logic
                                });
```
Also do you desire to have `Subsegment` inside recursive function ? Or is this you are looking for:
```
Parallel.ForEach(x, (y) => 
                                {
                                   AWSXRayRecorder.Instance.BeginSubsegment("test");
                                   recursiveFunc(); // business logic
                                   AWSXRayRecorder.Instance.EndSubsegment();
                                });
```

Please let me know if you have questions.

Best,
Yogi

**Comment by geraldbauer** [comment]
The recursive call follows this flow:
BeginProcess(...)
{
var results = SingleWork(...);
If (moreWork) results = DoMoreWork(...);

return results;
}

DoMoreWork(...)
{
Parrellel.ForEach
{
results.AddRange(BeginProcess(...));
}

return results;
}

**Comment by yogiraj07** [comment]
Hi @geraldbauer ,
As per above code, here are some initial thoughts for integration:
```
BeginProcess(...)
{

//If Segment already present in TraceContext, start a subsegment

var results = SingleWork(...);
If (moreWork) results = DoMoreWork(...);

// If segment was started close Segment else close Subsegment

return results;
}

DoMoreWork(...)
{
Parrellel.ForEach
{
results.AddRange(BeginProcess(...));
}

return results;
}
```

The result of this would be: 
1. If there was no Segment in the `TraceContext`, a `Segment` would be created in the first iteration and `Subsegment` would be created for each recursive call.

2. If `Segment` was already present in the `TraceContext`, `Subsegment` would be created for all iterations.

3. You can use `TraceContext.GetEntity()` method for getting `Segment/Subsegment` . :  https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/Internal/Utils/TraceContext.netstandard.cs#L40

Please let me know if you have question.

Best,
Yogi

**Comment by mbp** [comment]
The exception `Cannot add subsegment to a completed segment.` is quite problematic when you add AWS X-Ray .NET to an existing application with a lot of "background" jobs.

In my concrete scenario, the application has many background jobs, ensuring internal caches are updated. Since these background jobs are not based on an http request, they all fail with that exception. The code running the background jobs are in separate library packages, so it's not easy to go there and add `AWSXRayRecorder.Instance.BeginSegment(...)` calls.

First of all, it would be better if AWS X-Ray just provided a warning for this, and did not make the requests fail.
Second, it would be even better if it knew that this was part of a background job, and could send it to xray as trace data still.

**Comment by yogiraj07** [comment]
Hi @mbp ,
Apologies for delay in response. 

You can log error messages received by X-Ray SDK by setting environment variable `AWS_XRAY_CONTEXT_MISSING` to  `LOG_ERROR` for logging errors else the default behavior is to throw runtime exceptions for context missing. Reference (check `Environment Variables` sections): [Link](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-dotnet-configuration.html)

Can you help us understand how the main thread that serves request connect to the background jobs. Also is it possible to  create a `Subsegment` before starting a background job and close the `Subsegment` after the job is completed. In this way, even if the `Segment`  in the main thread closes, the `Subsegment` created in the background job gets attached to the `Subsegment` created before starting the background job. 
The above approach is implemented in [Asynchronous wrapper](https://github.com/aws/aws-xray-sdk-dotnet/tree/master#asynchronous-method). You can use this wrapper directly instead of manually creating `Subsegment`.

From X-Ray SDK perspective its difficult to distinguish between the in-app calls and background jobs since X-Ray SDK is agnostic to the value present in the `CallContext`.

We strive hard to make user experience as smooth as possible and appreciate your feedback.
Please let me know if you need more help.

Thanks,
Yogi

**Comment by mbp** [comment]
Thank you for the info on the environment variable, I somehow missed that.

> Can you help us understand how the main thread that serves request connect to the background jobs

Basically a request will add to some kind of in-memory data structure, and the background job will be a timer which processes the in-memory data structure and as a side-effect send some requests to AWS.

Thanks for the guidance on the environment variable.

**Comment by yogiraj07** [comment]
Hi @mbp ,
As a part of `2.3.0-beta` release we also have added support for setting `AWS_XRAY_CONTEXT_MISSING` using configuration file for .NET and .NET Core. Please refer : https://github.com/aws/aws-xray-sdk-dotnet/blob/master/CHANGELOG.md

I am closing this issue. Please feel free to reopen if you have any questions.

Best,
Yogi
