### ISSUE TITLE
Allow AWS_XRAY_CONTEXT_MISSING to be configured via IConfiguration

### ISSUE THREAD

**Issue by stevejgordon** [aws/aws-xray-sdk-dotnet#33]
I've just started trying out this library today. One thing I found annoying with the default for AWS_XRAY_CONTEXT_MISSING to cause a runtime error. I'd like to deploy this onto existing production apps to see if it proves useful, but it's slightly riskier since if I miss any places where SDK calls, for example, are made outside of a normal ASP.NET Core request flow, it throws.

I realise I can set the AWS_XRAY_CONTEXT_MISSING environment variable to control this, but that adds work to deployments and if missed could cause the app to fail, purely over tracing needs. I'd much prefer a silent failure as the default here.

An alternative (and I've not dug into the code deeply yet) is that it would be nice to control this setting from the settings available in appSettings.json so I can set the default to logging only which I know will be deployed with the app. We can then override with an environment variable if we prefer.

**Comment by yogiraj07** [comment]
Hi @stevejgordon ,
Thank you for your feedback. This is a good suggestion and I would take this as a feature request. As a side note, another way of configuring `AWS_XRAY_CONTEXT_MISSING` is by creating recorder instance through builder class and using `WithContextMissingStrategy ()`. Reference : https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/AwsXrayRecorderBuilder.cs#L151.

We also welcome you to submit PR.

Thanks,
Yogi

**Comment by stevejgordon** [comment]
Thanks Yogi. If time permits I may well look at getting you a PR for this one. I'm registering with the UseXray IApplicationBuilder extension in this case but I am also looking to add this to new Generic Host based console app services too. 

Perhaps either an overload for UseXray or a fluent style syntax would be suitable?

**Comment by yogiraj07** [comment]
Hi @stevejgordon ,
I think we can go with `UseXRay` convention, however, I would welcome your suggestion.

Best,
Yogi

**Comment by stevejgordon** [comment]
@yogiraj07 I took a quick look at this. From an early look, the smallest change here feels like we could add a property to XRayOptions which we can parse from IConfiguration in GetXRayOptions. Based on that value we can configure call WithContextMissingStrategy appropriately.

Does that sound reasonable?

One contributing question. I've not done a lot with multi-targeted libraries. I can see you are conditionally including/excluding the .netcore.cs files for example in the projects. I've not seen this done before and I'm unclear on how / if I can make VS play nice with the projects in this format. I get various warnings in VS currently, although it does build. Any tips for developing on this library?

**Comment by yogiraj07** [comment]
Hi @stevejgordon ,
Yes, we can add a property to `XRayOptions `, so we can use in `WithContextMissingStrategy()`.
We do suppress few warnings as a result of multi-target library in `Release` and `Debug` configuration [Link](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/AWSXRayRecorder.Core.csproj#L24). However, apart from that, I haven't had any specific VS setup (though using latest version of VS).

Please let me know if you would like to point out specific warnings. 

Best,
Yogi

**Comment by stevejgordon** [comment]
It's mostly symbols not being resolved etc:
![image](https://user-images.githubusercontent.com/3669103/41367906-49fe54cc-6f38-11e8-9706-f7da9c5eafdd.png)
I'm able to build though.

**Comment by yogiraj07** [comment]
Hi @stevejgordon ,
Unfortunately, I haven't encountered such problem. I would suggest cleaning `.nuget` cache folder from your system, restarting VS, cleaning and rebuilding the project. 

For reference: Current VS version I am using: `15.7.2`

**Comment by normj** [comment]
@stevejgordon That is weird you seeing those error in VS. What do the drop down boxes on top of the editor say? I'm curious if for some reason it is not saying netstandard2.0. I have seen where VS gets confused and just calls the files miscellaneous files.

![image](https://user-images.githubusercontent.com/1653751/41378652-90a8bd82-6f14-11e8-87e5-4360588272be.png)

**Comment by stevejgordon** [comment]
Aiming to try this on my work PC at lunchtime which will be a fresh attempt. Failing that I'll try the clean etc at home this weekend and see where I get to.

**Comment by stevejgordon** [comment]
@normj / @yogiraj07 - Still no luck at my end. Not sure if I'm doing something wrong but even after cleaning everything it's not picking up the correct files. For example, in VS I can code navigate to the AwsXrayRecorder.netcore.cs file, but it's not showing in solution explorer. I've added it and made some parts of the code happy but now get compilation errors. I'll keep trying a little longer but if there are steps I'm missing, I'd welcome pointers.

**Comment by stevejgordon** [comment]
@normj When in the .netcore.cs files I do see netstandard 2.0

**Comment by stevejgordon** [comment]
Actually, not sure exactly what I've changed but managed to get it building and debugging with a sample app so I may be getting somewhere!
