### ISSUE TITLE
Support for DB calls via Entity Framework Core

### ISSUE THREAD

**Issue by stevejgordon** [aws/aws-xray-sdk-dotnet#34]
Do you have any plans to add an Entity Framework Core handler? At the moment it feels like a big piece of the puzzle is missing for most of my APIs.

I have been testing the SDK / X-Ray for the first time today. I have just managed to hack together a basic piece of code based on what your SQL handler does. However, I'm using the DiagnosticListener to grab the EF core diagnostic events needed to start and stop a subsegment. It's actually working but I have a few concerns about how it would work if things are happening concurrently.

I've just forked the code so that I can look deeper into how things work. My main question is what happens if code executes concurrently, how do you ensure the correct subsegments are being closed off. It feels like there needs to be a principle of controlling which subsegment you are done with.

Ignoring for now what I'm doing with EF, if two SDK calls are made concurrently. The first one started takes 2 seconds and the second takes 5. How would the tracing know which is which when the EndSubSegment is called as they return?

As an aside, do you have a public roadmap for the SDK you would be able to share in terms of planned features, handles etc?

**Comment by normj** [comment]
Hey Steve, the X-Ray SDK relies on AsyncLocal under the covers to keep the segments separated per invocation request. There is no public roadmap but I agree Entity Framework and Entity Framework Core are important handlers we need.

**Comment by stevejgordon** [comment]
I'm just looking at that code now! I guess my question is, if these two things are triggered within the same async flow (say an ASP.NET Core request), how would the endsubsegment know which is actually being closed? Or do they have a unique id there?

I'll probably do best by reading the code properly!

I'm happy to put a rough PR in at some stage with the bits I've got so far. Even if it's a strawman for getting started with this. I've just hacked it into my code right now so I'd need to move it out to a proper handler.

**Comment by normj** [comment]
AsyncLocal does a lot of magical stuff storing things in thread local storage. At a high level it lets you treat the object it is holding as a singleton in the scope of a request.

**Comment by stevejgordon** [comment]
Yeah, AsyncLocal is a bit magic. My little correlation ID library leans on it too. My query though is two SDK calls occurring within that single request scope at roughly the same time. Or in the case of the EF example, if two DB calls start a subsegment and fire at the same time within that single requests cope, how is endsubsgement for each on them closing the correct one to end the timing on for example.

**Comment by yogiraj07** [comment]
Hi @stevejgordon ,

The linking of a segment and a subsegment is made using `Parent`: https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/Internal/Entities/Entity.cs#L474

If 2 DDB calls occur at the same time, they would be on different logical thread (considering the same time). The segment would be copied on individual DDB call request and the X-Ray SDK middleware will create and close subsegment in its entirety. This ensures the correctness of the subsegments.

A reference unit test that could help you understand : https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/test/UnitTests/AWSXRayRecorderTests.cs#L127

Please let me know if this answers your question.

**Comment by stimpy77** [comment]
This thread is a year old, X-Ray has been around for a couple years (++) now and this thread is linked from https://forums.aws.amazon.com/thread.jspa?threadID=309263 one of the first that comes up searching for: "AWS X-Ray" "SQL Server"

Can we please get an update on this? Or was this thread abandoned while the feature already implemented?

**Comment by srprash** [comment]
Hi @stimpy77 ,
Supporting Entity Framework calls is on our backlog. I'm really sorry we couldn't get it prioritized till now. Please stay tuned for updates.

Thanks.

**Comment by dkleczko** [comment]
Hi @srprash great to hear that it's time for this feature.
Have you any ETA for this? Could you also verify will it works for configuration Entity Framework Core + Pomelo.EntityFrameworkCore.MySql?

**Comment by srprash** [comment]
Hi @dkleczko We are hoping to roll it out soon but cannot promise an ETA at this moment. We do plan to support the Pomelo.EntityFrameworkCore.MySql provider for EntityFrameworkCore.

**Comment by emonhaider** [comment]
> Hi @dkleczko We are hoping to roll it out soon but cannot promise an ETA at this moment. We do plan to support the Pomelo.EntityFrameworkCore.MySql provider for EntityFrameworkCore.

Any update on this?

**Comment by srprash** [comment]
Hi @emonhaider 
I got pulled away from working on this for some time. I sincerely apologize for that. I have the bandwidth now to take it back up. Please stay tuned for updates.

**Comment by lupengamzn** [comment]
> > Hi @dkleczko We are hoping to roll it out soon but cannot promise an ETA at this moment. We do plan to support the Pomelo.EntityFrameworkCore.MySql provider for EntityFrameworkCore.
> 
> Any update on this?

Hi @emonhaider 
We are currently working on extending AWS XRay .NET SDK's features to trace sql queries through EF Core. Please stay tuned for further updates.

**Comment by lupengamzn** [comment]
Support tracing for Entity Framework Core 3.0 and above will be included in next version which will be released soon #124

**Comment by priorax** [comment]
@lupengamzn  - I was about to try and implement this in my project, but noticed that this issue is still open, but the commit appears merged + released.
Is it still pending a release, or has this shipped and the issue not closed?

**Comment by srprash** [comment]
Hi @priorax 
The EFCore support has been released in v2.8.0 as a new handler [package](https://www.nuget.org/packages/AWSXRayRecorder.Handlers.EntityFramework/). You can find the usage guide on our README. 
Thanks!
