### ISSUE TITLE
Can't target asp.net core on .net framework

### ISSUE THREAD

**Issue by dr3s** [aws/aws-xray-sdk-dotnet#39]
According to this issue https://github.com/aws/aws-xray-sdk-dotnet/issues/36 , it is not possible to target asp.net core on .net framework.  Since this is the recommended stack for new .net framework development, I think it should be supported.

**Comment by yogiraj07** [comment]
Hi @dr3s ,
Thank you for opening issue. I added this item to feature request. At the moment, I would need to figure out how to target  X-Ray ASP.NET Core handler : [Link](https://www.nuget.org/packages/AWSXRayRecorder.Handlers.AspNetCore/2.2.1-beta) on `.NET platform` as it currently only supports `.NET Core platform`.

In the meantime, we welcome you to submit a PR, if interested.
Thanks,
Yogi

**Comment by jaredcnance** [comment]
ASP.Net Core will only run on .Net Core after v3. See [this announcement](https://github.com/aspnet/Announcements/issues/324).

**Comment by yogiraj07** [comment]
Hi @dr3s ,

Considering the support won't be available in [ASP.NET Core 3.0](https://github.com/aspnet/Announcements/issues/324), we currently don't plan to work on this feature. 

Thanks @jaredcnance  for the information.

Please feel free to submit PR specifically for ASP.NET Core 2.0. I am happy to review it. Closing this issue for now.
