### ISSUE TITLE
Support tracing of HTTP requests using HttpClient

### ISSUE THREAD

**Issue by ljacobsson** [aws/aws-xray-sdk-dotnet#4]
Feature request.

Currently the SDK only supports out-going HTTP requests using the `HttpWebRequest` client. It would be useful having tracing capabilities for those using `System.Net.HttpClient`.

For now I've created a [custom MessageHandler](https://github.com/mhlabs/MhLabs.AWSXRayHttpClientHandler/tree/master) for this, but would be great to have this or something similar as part of the SDK.

Edit: I just noticed that this has already been requested in #3.

I will look at adding that as a pull request

**Comment by yogiraj07** [comment]
Hi @ljacobsson ,
Thank you for the feature suggestion. We welcome your pull request.

Thanks,
Yogi

**Comment by SergeyKanzhelev** [comment]
You can use [Diagnostics Source](https://github.com/dotnet/corefx/blob/b3033e6bd586fb7bdc2e1afdd1694e790272ce6e/src/System.Net.Http/src/HttpDiagnosticsGuide.md) to get information about outgoing http calls.

**Comment by yogiraj07** [comment]
Hi @ljacobsson ,

We have included this feature in `2.2.0-beta` release.

Please refer release details : https://github.com/aws/aws-xray-sdk-dotnet/blob/master/CHANGELOG.md

I am closing this issue.

Thanks,
Yogi
