### ISSUE TITLE
HybridContext Implementation for ASP.NET Framework

### ISSUE THREAD

**Issue by yogiraj07** [aws/aws-xray-sdk-dotnet#43]
# Problem
For X-Ray .NET SDK version <= `2.3.1-beta`,  ASP.NET XRay middleware used`TraceContext` that implemented [CallContext](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.remoting.messaging.callcontext?view=netframework-4.5) as an underlying data structure. This `CallContext` stored `Segment`/`Subsegment` created for the given lifecycle of incoming HTTP request.  Value (Segment/Subsegment) in `CallContext`  for `POST` request with certain payload is lost resulting  in`EntityNotAvailableException`. This behavior is unpredictable. 

Reference : [issue#26](https://github.com/aws/aws-xray-sdk-dotnet/issues/26)

# Analysis
1. After some research, it became apparent that, it is not guaranteed the same thread serves [incoming request](https://blogs.msdn.microsoft.com/ploeh/2007/07/28/call-contexts-vs-asp-net/) for ASP.NET framework.
2. For the above described issue, ASP.NET framework makes a thread switch while processing `POST` request. This thread switch results in `CallContext` value to be lost in the controller that handles `POST` request. The CallContext value is not propagated due to ASP.NET thread pooling.
3. As a result, `Segment` stored in `CallContext` at the start of incoming request is not available in the controller, that results in exception for creating `Subsegment`.

# Research
1. [HttpContext](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpcontext?view=netframework-4.7.2) object  is per incoming HTTP request and data stored in `HttpContext.Items` is persisted across components of ASP.NET.
2. As per official documentation, this HttpContext object is only available in the thread controlled by ASP.NET. Usage in background threads could lead to undefined behavior.
3. This object is ready for garbage collection when the HttpRequest is completed. Its usage after the request completes could lead to undefined behavior, such as a NullReferenceException.

# Solution
Instead of using only `CallContext` , `TraceContext` now uses `HybridContext` : `CallContext` for all CRUD operations on `Entity` (Segment/Subsegment) and `HttpContext.Items` to store the `Segment` started by ASP.NET X-Ray middleware. 

At any point if the `CallContext` doesn't have value, `Segment` reference is copied from `HttpContext` to `CallContext`. This results in restoring already created `Segment-Subsegment` hierarchy and new `Subsegment` will be attached to the current `Segment`.

The implementation is available [here](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/Internal/Context/HybridContextContainer.net45.cs) and is released in version `2.4.0-beta` [Changelog](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/CHANGELOG.md).

ASP.NET X-Ray middleware by default now uses `HybridContextContainer`.

### Limitation
For the `POST` request, if `async` task is directly started in the controller, without using X-Ray wrapper [TraceMethodAsync](https://github.com/aws/aws-xray-sdk-dotnet/tree/master#asynchronous-method), the application may experience `EntityNotAvailableException`.  The `HttpContext` has the segment before starting `async` task, however, `CallContext` doesn't (due to above issue) and the `HttpContext` may not be propagated to `async` task.

### Workaround
[InjectEntityInTraceContext](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/Internal/Context/HybridContextContainer.net45.cs#L146) method should be explicitly called before spawning `async` task. This method ensures, `Segment` reference is copied from `HttpContext` to `CallContext` and `CallContext` get propagated to the following `async` task.

We would appreciate if you have any feedback/suggestions.

Thanks,
Yogi

**Comment by mpetito** [comment]
Why aren't you using the dependency injection container in ASP.NET Core?  It seems like a poor design choice to use the "ambient context" approach when ASP.NET Core and all of its related modules provide DI support that could better suppor this use-case.

**Comment by yogiraj07** [comment]
Hi @mpetito ,
The above issue and approach of hybrid context is specific to ASP.NET framework and not ASP.NET Core framework. The ASP.NET Core uses `AsyncLocal` and X-Ray [middleware](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Handlers/AspNetCore/Internal/AWSXRayMiddleware.cs).

Please let me know if I miss something.

Thanks,
Yogi
