### ISSUE TITLE
Question: Lambda "Enable active tracing"

### ISSUE THREAD

**Issue by anandmukundan** [aws/aws-xray-sdk-dotnet#44]
Hi,

You can enable/disable active tracing at a Lambda function level, using the console. Is there a way to find out what is the option that has been set during Lambda execution? I have some additional Xray tracing code, which I do not want to run when this option is disabled in the console as then the default segment is not created by the Lambda function.

If I look at the IsTracingDisabled Function, it always returns false, even if this option is disabled in the console. Looks like this picks the value from the app settings and not the console settings.

Is there a way to check what is the setting in the console/lambda function level?

**Comment by awssandra** [comment]
Hi anandmukundan,

Sorry for the extended delay. Lambda does not give the SDK any notion of wether the Lambda function is in active or passthrough mode. Feel free to open a discussion on the Lambda forums. I'm sure they would be interested in your usecase.

Thanks!
Sandra
