### ISSUE TITLE
XRay throws exceptions when running integration tests which create additional Hosts

### ISSUE THREAD

**Issue by rschiefer** [aws/aws-xray-sdk-dotnet#52]
I can run any of my integration tests (based on nUnit) individually and they succeed.  But when I run them all I receive the following error on further tests after a new Host is built by one of the tests:

> Amazon.XRay.Recorder.Core.Exceptions.EntityNotAvailableException : Entity doesn't exist in AsyncLocal

I'm assuming this is because XRay data is stored statically and assumes only one Host will be created.

Any suggestions to work around this?

**Comment by yogiraj07** [comment]
Hi @rschiefer ,

X-Ray data is stored in [AsyncLocal](https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1?view=netcore-2.0) for .NET Core platform, which is thread based.

The reason for this exception is Segment/Subsegment might have already ended before performing any operation on the recorder instance.

1. For clarification, do you see this exception from the integration test which tests X-Ray instrumented code ? Are you using any X-Ray middleware that your test is using?
2. Any code snippet for your test/ X-Ray instrumented code (please redact sensitive information)
3. Can you explain more on ` a new Host is built by one of the tests` ?  

Thanks,
Yogi

**Comment by yogiraj07** [comment]
Hi @rschiefer ,
Please feel free to re-open this issue if you need help.
