### ISSUE TITLE
Optimize dependencies for RegisterXRayForAllServices()

### ISSUE THREAD

**Issue by bjorg** [aws/aws-xray-sdk-dotnet#54]
I added these two lines to my `.csproj` file so I could invoke `AWSSDKHandler.RegisterXRayForAllServices()`:
```xml
    <PackageReference Include="AWSXRayRecorder.Core" Version="2.5.0"/>
    <PackageReference Include="AWSXRayRecorder.Handlers.AwsSdk" Version="2.5.0"/>
```

It resulted in a surprising amount of dependencies being pulled in
```
  Installing runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2.
  Installing runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2.
  Installing runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2.
  Installing runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2.
  Installing runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2.
  Installing runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2.
  Installing runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2.
  Installing runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2.
  Installing runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2.
  Installing runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2.
  Installing Microsoft.AspNetCore.Http.Features 2.0.0.
  Installing runtime.native.System.Security.Cryptography.OpenSsl 4.3.2.
  Installing Microsoft.AspNetCore.Http.Abstractions 2.0.0.
  Installing Microsoft.Net.Http.Headers 2.0.0.
  Installing Microsoft.Extensions.Options 2.0.0.
  Installing Microsoft.AspNetCore.WebUtilities 2.0.0.
  Installing AWSXRayRecorder.Core 2.5.0.
  Installing AWSXRayRecorder.Handlers.AwsSdk 2.5.0.
  Installing AWSSDK.XRay 3.3.3.
  Installing AWSSDK.Core 3.3.25.1.
  Installing Microsoft.Extensions.Configuration 2.0.0.
  Installing Microsoft.AspNetCore.Http 2.0.0.
  Installing System.Net.Http 4.3.3.
  Installing Microsoft.Extensions.Configuration.Abstractions 2.0.0.
```

Maybe the ASP.NET Core dependencies could be omitted by moving them to a specialized package?

**Comment by yogiraj07** [comment]
Hi @bjorg ,
AWSXRayRecordeCore package depends on [Microsoft.AspNetCore.Http](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/AWSXRayRecorder.Core.csproj#L47) for the purpose of [SegmentNamingStrategy](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/Strategies/DynamicSegmentNamingStrategy.cs#L135). All X-Ray packages depend on this packages for operations related to X-Ray. Can you provide more insights on decoupling AspNerCore.Http dependency.

I would be happy to review PR.

Thanks,
Yogi

**Comment by bjorg** [comment]
My concern is simply about minimizing the size of the required packages. This dependency brings in a lot of additional code, as you can see, for non-ASP.NET Core functions. I surprised me when I saw this and thought it may have been unintentional.

**Comment by yogiraj07** [comment]
Hi @bjorg ,
Sure . I understand your point. However, the [dependencies](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/AWSXRayRecorder.Core.csproj#L45) for AWSXRayRecorderCore package are required for NETCore platform to provide core functionalities on `AWSXRayRecorder` instance. As per above explanation, [Microsoft.AspNetCore.Http](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/AWSXRayRecorder.Core.csproj#L47) cannot be eliminated. Moreover,`AWSXRayRecorder.Handlers.AwsSdk` depends on `AWSXRayRecorder.Core` and uses many core functions to capture AWS SDK calls.

Thanks,
Yogi

**Comment by bjorg** [comment]
@yogiraj07 Understood. Just wanted to raise awareness in case it was unintentional.

**Comment by normj** [comment]
Actually I think the big problem is the AWSSDK.Core targets netstandard1.3 which brings in unnecessary dependency when combined with a netstandard2.0 library like the XRay SDK.

We just fixed this in the Amazon Lambda NuGet packages. We are planning on doing the same with the AWSSDK NuGet packages soon as well. Once we do that we should bump the version of the SDK XRay depends on.
