### ISSUE TITLE
Lambda x-ray trace missing request information

### ISSUE THREAD

**Issue by djluck** [aws/aws-xray-sdk-dotnet#56]
When capturing X-Ray trace information for my ASP.NET core 2.1 WebAPI application, request information is missing (e.g. url, user agent, etc):

![image](https://user-images.githubusercontent.com/1540536/52985133-7e21a500-3446-11e9-8be4-d1e1c2b91b14.png)

Looking at the raw JSON of a trace, it seems there are two subsegments, one for the request and one for the response (sensitive information has been scrubbed):

```
{
    "Duration": 0.814,
    "Id": "1-5c6b564b-40eca8a7451d03810d3da705",
    "Segments": [
        {
            "Document": {
                "id": "23dbc54b6e683eaa",
                "name": "[OMITTED]",
                "start_time": 1550538315.511,
                "end_time": 1550538316.315,
                "parent_id": "059037fcdf2fb610",
                "aws": {
                    "function_arn": "[OMITTED]",
                    "resource_names": [
                        "[OMITTED]"
                    ],
                    "account_id": "[OMITTED]"
                },
                "trace_id": "1-5c6b564b-40eca8a7451d03810d3da705",
                "origin": "AWS::Lambda::Function",
                "subsegments": [
                    {
                        "id": "98262d52ae5e1959",
                        "name": "[OMITTED]",
                        "start_time": 1550538315.511743,
                        "end_time": 1550538316.315486,
                        "http": {
                            "request": {
                                "url": "[OMITTED]",
                                "method": "GET",
                                "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
                                "client_ip": "[OMITTED]",
                                "x_forwarded_for": true
                            },
                            "response": {
                                "status": 0
                            }
                        }
                    }
                ]
            },
            "Id": "23dbc54b6e683eaa"
        },
        {
            "Document": {
                "id": "059037fcdf2fb610",
                "name": "[OMITTED]",
                "start_time": 1550538315.504,
                "end_time": 1550538316.318,
                "http": {
                    "response": {
                        "status": 200
                    }
                },
                "aws": {
                    "request_id": "e9520324-cd8f-40c5-a5c9-849adc02163f"
                },
                "trace_id": "1-5c6b564b-40eca8a7451d03810d3da705",
                "origin": "AWS::Lambda",
                "resource_arn": "[OMITTED]"
            },
            "Id": "059037fcdf2fb610"
        }
    ]
}
```

Does this look valid? It seems that AWS x-ray is having issues understanding this format.

**Comment by chanchiem** [comment]
Hey, 

It looks like the request information is propagated down to the subsegment with the ID "98262d52ae5e1959". So far everything seems to look valid.

I believe the reason why it's not showing up in the console is because your endpoint is not being traced. If you're using API gateway to invoke the Lambda method, I would recommend enabling tracing on your endpoint to ensure that the URL information is propagated to that endpoint which will then show up on the console as expected. Let me know if you need instructions on how to do that. The SDK cannot modify Lambda segments because they are generated automatically by the Lambda container, so that would explain why you don't see it in those segments other than their subsegments.

Let me know if this helps!
Thanks!

**Comment by djluck** [comment]
@chanchiem thank you, that indeed fixed the issue! I thought I just had to enable tracing on the lambda, not just Api gateway- thanks for your help.
