### ISSUE TITLE
Add option to register XRay manifest from embedded resource

### ISSUE THREAD

**Issue by sergedomk** [aws/aws-xray-sdk-dotnet#61]
Version: 2.5.0 (issue still exists on master)

I'm attempting to create a NuGet package for internal use that takes care of some of the XRay setup we are adding to a number of applications/services.

One of the requirements is adding some Secrets Manager calls to the whitelist. In fact, it was the primary reason for creating an internal library. That, and a DB profiler that worked on our PostgreSQL DB connections. Unfortunately, contentFiles are not pulled into projects that don't use project.json (https://blog.nuget.org/20160126/nuget-contentFiles-demystified.html - See section : Supported Project Types). In our case, this is almost all of them.

As, the SDK offers no option to pull in a manifest other than from file, I'm going to have to resort to taking my embedded manifest document from my NuGet package and streaming it to disk so I can then feed the path to the RegisterXRayManifest() method.

Ideally I would be able to register the embedded resource directly similar to how the DefaultAWSWhitelist.json resource is handled in InitWithDefaultAWSWhitelist() method in Handlers/AwsSdk/Internal/XRayPipelineHandler.cs or via a more generic approach that allows for passing a stream to RegisterXRayManifest().

**Comment by yogiraj07** [comment]
Hi @sergedomk ,
Thank you for explaining the use case. 
I feel going with generic approach and adding a new method on `RegisterXRayManifest(string manifestName)` in this [class](https://github.com/aws/aws-xray-sdk-dotnet/blob/8053d17f191d40cbabb18b4cb20b6d6ff6cfb44f/sdk/src/Handlers/AwsSdk/AWSSDKHandler.cs#L63) will help.

I think we need to use [GetManifestResourceStream](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getmanifestresourcestream?redirectedfrom=MSDN&view=netframework-4.7.2#System_Reflection_Assembly_GetManifestResourceStream_System_String_) to read the stream. 

Please let me know your thoughts, I will take this as a feature request and a PR is always welcomed.

Thanks,
Yogi

**Comment by sergedomk** [comment]
@yogiraj07 ,

Just to make sure I understand, I'm going to attempt to illustrate the approach I'm going to take. If it doesn't match with your thinking, I'd appreciate your feedback.

In [AWSSDKHandler.cs](https://github.com/aws/aws-xray-sdk-dotnet/blob/8053d17f191d40cbabb18b4cb20b6d6ff6cfb44f/sdk/src/Handlers/AwsSdk/AWSSDKHandler.cs#L63), I would add:

`public static void RegisterXRayManifest(Stream stream)`

Looking at how the customizer logic worked, it appears that a little restructuring would be required to prevent having to leave the `stream` open. To prevent this, I'm thinking of replacing `Path` with the `XRayPipelineHandler` on the customizer so that `RegisterXRayManifest()` can do the following:

` _customizer.XRayPipelineHandler = new XRayPipelineHandler(path)`
` _customizer.XRayPipelineHandler = new XRayPipelineHandler(stream)`

Does this match up with your thinking?

P.S. - I cloned the repo and opened the Solution in VS, I have a handful of tests failing including all of the integration tests. Are there some special requirements required to run the tests?

**Comment by yogiraj07** [comment]
@sergedomk ,
I think above logic is correct. We can have `XRayPipelineHandler` instance member on `_customizer` class. We can also add unit tests for the same. 

Can you specify what exact error you are getting for unit tests?

I have netcore 2.0 installed and I run `dotnet test` command inside both unit and integration tests folder. This runs tests against net45 and netcore 2.0 platform. For integration tests, you would need to run X-Ray [Daemon](https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-local.html) locally so that the segments generated by integration tests reach X-Ray service. Running `xray.exe` would work. You would need to run the daemon in `us-east-1` region.

**Comment by yogiraj07** [comment]
Hello,
This has been added in release `2.6.0`. Please refer [Changelog](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/CHANGELOG.md).
