### ISSUE TITLE
Readme error on NuGet package name

### ISSUE THREAD

**Issue by steveataws** [aws/aws-xray-sdk-dotnet#78]
The *How to use > Incoming requests* section lists the wrong NuGet package name in step 2. It states you should install a package named **Amazon.XRay.Recorder.Handlers.AspNetCore**. The package is actually named **AWSXRayRecorder.Handlers.AspNetCore**.

**Comment by yogiraj07** [comment]
@steveataws , thanks for pointing out. Will revisit all package names on the read me.

**Comment by srprash** [comment]
Updated the Readme to correct this.
