### ISSUE TITLE
Don't set MaxStackFrameSize to 50 in a const variable like you do now for Exception handling

### ISSUE THREAD

**Issue by PaulDMendoza** [aws/aws-xray-sdk-dotnet#8]
The max stack frame size is cutting off the interesting bits of my Exception. If you could make that value at least configurable somehow or make it a public static value that I could set on application start that would allow me to capture more Exception details than I'm getting now. The value is currently hardcoded to 50. I haven't found any XRay docs stating 50 is a limit for the stack frame limit.

https://github.com/aws/aws-xray-sdk-dotnet/blob/191a7f085cbb8eb3e2a2121754d057db1f095e05/sdk/src/Core/Internal/Entities/Cause.cs

**Comment by yogiraj07** [comment]
Hi @PaulDMendoza ,
This feature has been release in `2.5.0`. Please refer [Changelog](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/CHANGELOG.md).

Thanks,
Yogi
