### ISSUE TITLE
Exceptions with no daemon and trace disabled

### ISSUE THREAD

**Issue by okubiak** [aws/aws-xray-sdk-dotnet#80]
Hello,

I'm using AWSXRayRecorder v2.6.1 and ASP.Net Core 2.1.
XRay is initialized with:
```
AWSXRayRecorder.RegisterLogger(LoggingOptions.Log4Net);
AWSXRayRecorder.InitializeInstance(_configuration);
AWSSDKHandler.RegisterXRayForAllServices();
```

Is it intended to have the client connected to the daemon (and polling SamplingStrategy) even if trace is disabled?

Today if I don't have a xray daemon running and with trace disabled (`IsXRayTracingDisabled = true`) I'm spammed by exceptions (connection and polling).

Any way to disable it completely for testing purpose? Like for local or load-test environment.

Regards

**Comment by yogiraj07** [comment]
@okubiak ,
You can configure the AWSXRayRecorder instance with [LocalizedSamplingStrategy](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/Sampling/Local/LocalizedSamplingStrategy.cs#L35), similar to this [code](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/test/UnitTests/AWSXRayRecorderTests.cs#L970) and this will not start X-Ray pollers that connects to daemon in your testing environment.

On the side note I think we need optimization to not start pollers when `IsXRayTracingDisabled = true`. This is a good callout and I will take this as a feature request.

**Comment by yogiraj07** [comment]
Hi @okubiak ,
Created a separate issue to ease the user experience : #86 . Please feel free to open if you have questions.

Best,
Yogi
