### ISSUE TITLE
TraceableSqlCommand fails on trusted connections

### ISSUE THREAD

**Issue by stolemotion** [aws/aws-xray-sdk-dotnet#81]
In TraceableSqlCommand.cs the recorder assumes that UserID is present in the connectionstring in the line:

`recorder.AddSqlInformation("user", connectionStringBuilder.UserID);`

But for trusted connections this is not the case and an exception occurs.

**Comment by yogiraj07** [comment]
Hi @stolemotion ,
Thanks for reporting the issue. 
I believe we should do a check if `UserID` is present for `connectionStringBuilder`. 
Can you paste the exception stack trace ? For trusted connection can you provide an example on how to produce this scenario (basically how you made the call)?

**Comment by srprash** [comment]
Hi @stolemotion ,
This issue has been fixed in v2.7.0
Please refer to the [Changelog](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/CHANGELOG.md) for details.

Thanks,
Prashant
