### ISSUE TITLE
Don't start pollers when tracing is disabled

### ISSUE THREAD

**Issue by yogiraj07** [aws/aws-xray-sdk-dotnet#86]
# Background
2 pollers are started in the background for DefaultSamplingStrategy
1.  When the first incoming request for the framework arrives : [code](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/Sampling/DefaultSamplingStrategy.cs#L102)
2. `BeginSegment()` makes a sampling decision : [code](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/AWSXRayRecorderImpl.cs#L164)

# Issue
When tracing is disabled using X-Ray SDK [Configuration](https://github.com/aws/aws-xray-sdk-dotnet/tree/master#configuration) or by creating custom recorder instance, the pollers are still started. Reference : #80 

# Expected Behavior
Pollers should not be started when tracing is disabled,

# Usecase
1. For unit testing, user can disable tracing. 
2. For various stages such dev , alpha, beta customers may not want to enable X-Ray and not launch the X-Ray daemon. In the current scenario, pollers are unnecessary started leading to using resources.

# Solution
Add [IsTracingDisabled()](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/AWSXRayRecorderImpl.cs#L250) check in the [ShouldTrace()](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/Sampling/DefaultSamplingStrategy.cs#L102) before starting poller.

**Comment by srprash** [comment]
Fixed in v2.7.0
Please refer to the [Changelog](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/CHANGELOG.md)
