### ISSUE TITLE
Signature of TraceMethodAsync shoud probably be async Task instead of async void

### ISSUE THREAD

**Issue by PaulDMendoza** [aws/aws-xray-sdk-dotnet#9]
I was trying to use the async method **TraceMethodAsync** and noticed it has a return type of void. Generally with C# methods that are async that don't return anything should have a return type of Task, not void unless they're event handlers. Your code might actually be handling it okay but it would be better to just return Task since that is the C# best practice. 

https://haacked.com/archive/2014/11/11/async-void-methods/

https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

*Async void methods have different error-handling semantics. When an exception is thrown out of an async Task or async Task<T> method, that exception is captured and placed on the Task object. **With async void methods, there is no Task object, so any exceptions thrown out of an async void method will be raised directly on the SynchronizationContext that was active when the async void method started. Figure 2 illustrates that exceptions thrown from async void methods can’t be caught naturally.***

**Comment by yogiraj07** [comment]
Hi @PaulDMendoza ,

We appreciate your feedback and will consider this in future release.

Thank you,
Yogi

**Comment by yogiraj07** [comment]
Hi @PaulDMendoza ,

We have modified the signature  for`TraceMethodAsync()` method in release `2.1.0-beta`.
Thank you for your suggestion and we welcome you to submit pull request for any desired features.

Changelog : https://github.com/aws/aws-xray-sdk-dotnet/blob/master/CHANGELOG.md

I am closing this issue.

Yogi
