### ISSUE TITLE
DefaultExceptionSerializationStrategy Throw System.NullReferenceException

### ISSUE THREAD

**Issue by czd890** [aws/aws-xray-sdk-dotnet#96]
Occasionally throw exceptions:
AWSXRayRecorder.Handlers.AspNetCore : 2.6.0

```shell
Microsoft.AspNetCore.Server.Kestrel ERROR 58  Connection id "0HLOVUBU82R61", Request id "0HLOVUBU82R61:00000048": An unhandled exception was thrown by the application. 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Amazon.XRay.Recorder.Core.Strategies.DefaultExceptionSerializationStrategy.<>c__DisplayClass14_0.<DescribeException>b__3(ExceptionDescriptor d)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Amazon.XRay.Recorder.Core.Strategies.DefaultExceptionSerializationStrategy.DescribeException(Exception e, IEnumerable`1 subsegments)
   at Amazon.XRay.Recorder.Core.Internal.Entities.Entity.AddException(Exception e)
   at Amazon.XRay.Recorder.Core.AWSXRayRecorderImpl.AddException(Exception ex)
   at Amazon.XRay.Recorder.Handlers.AspNetCore.Internal.AWSXRayMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by yogiraj07** [comment]
Hi @czd890 ,
As per the stack trace above the null reference exception is generated at this point of the [code](https://github.com/aws/aws-xray-sdk-dotnet/blob/bdb7471e2f14fc58da591321f08b3979729f0eb2/sdk/src/Core/Strategies/DefaultExceptionSerializationStrategy.cs#L135). However can you provide detail exception stack trace? If this is the exception being logged, a small repro example would be helpful. We haven't had this issue reported previously so would to need dive deep into this issue. 

A basic idea of your solution stack, and  when this is triggered will be helpful. Is it when you have specific behavior in the application workflow during which causes above exception (since its occasional)? 

My initial guess is ASP.NET Core X-Ray middleware is recording an exception which causes above unexpected behavior. 

Thanks,
Yogi

**Comment by czd890** [comment]
Local debugging cannot retry this problem.


Mybe d is null on existingExceptionDescriptors.FirstOrDefault(d => d.Exception.Equals(e));
https://github.com/aws/aws-xray-sdk-dotnet/blob/bdb7471e2f14fc58da591321f08b3979729f0eb2/sdk/src/Core/Strategies/DefaultExceptionSerializationStrategy.cs#L192

or e is null on FirstOrDefault(descriptor => e.Equals(descriptor.Exception))

https://github.com/aws/aws-xray-sdk-dotnet/blob/bdb7471e2f14fc58da591321f08b3979729f0eb2/sdk/src/Core/Strategies/DefaultExceptionSerializationStrategy.cs#L150

**Comment by czd890** [comment]
Tracked to where the error was thrown.

Usage custom ExceptionSerializationStrategy, The code Copy from `DefaultExceptionSerializationStrategy`. 
Change 
```C#
ExceptionDescriptor innerExceptionDescriptor = existingExceptionDescriptors != null ? existingExceptionDescriptors.FirstOrDefault(d => d.Exception.Equals(e)) : null;

// to

ExceptionDescriptor innerExceptionDescriptor = existingExceptionDescriptors != null ? existingExceptionDescriptors.FirstOrDefault(d =>
{
    if (d == null)
    {
       //add log to local file
      // tracked 'd' is null.
    }
    return d.Exception.Equals(e);
}) : null;

```
```C#
AWSXRayRecorder.Instance.ExceptionSerializationStrategy = new MyExceptionSerializationStrategy
```

**Comment by czd890** [comment]
I think this should be a matter worthy of further investigation. What can I help you?

**Comment by yogiraj07** [comment]
I think, while processing InnerException, e is set to [null](https://github.com/aws/aws-xray-sdk-dotnet/blob/bdb7471e2f14fc58da591321f08b3979729f0eb2/sdk/src/Core/Strategies/DefaultExceptionSerializationStrategy.cs#L196). Prior to reaching this point, we record this value as reference in [curDescriptor](https://github.com/aws/aws-xray-sdk-dotnet/blob/bdb7471e2f14fc58da591321f08b3979729f0eb2/sdk/src/Core/Strategies/DefaultExceptionSerializationStrategy.cs#L166), the value is null. This might be the probable cause for your scenario. Let me know what you think.

I think we should create a deep copy of the exception : [here](https://github.com/aws/aws-xray-sdk-dotnet/blob/bdb7471e2f14fc58da591321f08b3979729f0eb2/sdk/src/Core/Strategies/DefaultExceptionSerializationStrategy.cs#L166). Let me know what you think?

We can also cover this unit test I guess. 

Best,
Yogi

**Comment by czd890** [comment]
Seen from [DescribeException](https://github.com/aws/aws-xray-sdk-dotnet/blob/bdb7471e2f14fc58da591321f08b3979729f0eb2/sdk/src/Core/Strategies/DefaultExceptionSerializationStrategy.cs#L135) method, `d.Exception` should not have a `null` case.

**Comment by srprash** [comment]
> Seen from [DescribeException](https://github.com/aws/aws-xray-sdk-dotnet/blob/bdb7471e2f14fc58da591321f08b3979729f0eb2/sdk/src/Core/Strategies/DefaultExceptionSerializationStrategy.cs#L135) method, `d.Exception` should not have a `null` case.

Hi @czd890 , I did not fully understand this. Also, would it be possible for you to provide a sample code that reproduces this issue. It would be very helpful.

Thanks,
Prashant

**Comment by czd890** [comment]
Hi @srprash , Maybe related to no async task.
```C#
void execute(){
Task.Run(()=>{
AWSXRayRecorder.Instance.BeginSubsegment....
AWSXRayRecorder.Instance.EndSubsegment....
AWSXRayRecorder.Instance.AddException....
});
}
```

**Comment by bhautikpip** [comment]
Hi @czd890,

I was looking through the thread. I found it difficult to catch up. Would you mind explaining about this issue in detail? And also repro steps of this issue would be helpful.

**Comment by srprash** [comment]
Closing this one due to inactivity. Please reopen if you still face the issue. Thanks!

**Comment by DamirAinullin** [comment]
Sporadically get similar exception in AWS Lambda:
```
{
            "Depth": 0,
            "ClassName": "System.NullReferenceException",
            "Message": "Object reference not set to an instance of an object.",
            "Source": "AWSXRayRecorder.Core",
            "StackTrace": [
                "   at Amazon.XRay.Recorder.Core.Strategies.DefaultExceptionSerializationStrategy.<>c__DisplayClass14_0.<DescribeException>b__3(ExceptionDescriptor d)",
                "   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)",
                "   at Amazon.XRay.Recorder.Core.Strategies.DefaultExceptionSerializationStrategy.DescribeException(Exception e, IEnumerable`1 subsegments)",
                "   at Amazon.XRay.Recorder.Core.Internal.Entities.Entity.AddException(Exception e)",
                "   at Amazon.XRay.Recorder.Core.AWSXRayRecorderImpl.AddException(Exception ex)",
                "   at OS33.Serverless.Core.AwsLambda`2.LambdaHandler(TData data, ILambdaContext context)"
            ],
            "HResult": -2147467261,
            "HelpURL": null
        }
```

Lambda is called by Cloufwatch Event by timer every five minutes. Can you help fix this bug? Any workarounds?

**Comment by rpopovych** [comment]
Also getting this exception,
```
Amazon.XRay.Recorder.Core.Strategies.DefaultExceptionSerializationStrategy+<>c__DisplayClass14_0.<DescribeException>b__3 at , 0
System.Linq.Enumerable.TryGetFirst at , 0
System.Linq.Enumerable.FirstOrDefault at , 0
Amazon.XRay.Recorder.Core.Strategies.DefaultExceptionSerializationStrategy.DescribeException at , 0
Amazon.XRay.Recorder.Core.Internal.Entities.Entity.AddException at , 0
Amazon.XRay.Recorder.Core.AWSXRayRecorderImpl.AddException at , 0
Amazon.XRay.Recorder.Core.AWSXRayRecorderImpl+<TraceMethodAsync>d__77.MoveNext at , 0
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw at , 0
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification at , 0
...
Application code
...
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw at , 0
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification at , 0
Amazon.XRay.Recorder.Core.AWSXRayRecorderImpl+<TraceMethodAsync>d__77.MoveNext at , 0
```

In our case, it's failing to handle an exception from DynamoDB:

```
Throughput exceeds the current capacity of your table or index. DynamoDB is automatically scaling your table or index so please try again shortly. If exceptions persist, check if you have a hot key: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-design.html
```

**Comment by tmitchel2** [comment]
Also getting this exception.  Stack trace is exactly the same as above.

**Comment by Happi-cat** [comment]
getting same on awsxrayrecorder.core 2.10.1 
```
System.NullReferenceException: Object reference not set to an instance of an object.
    at Amazon.XRay.Recorder.Core.Strategies.DefaultExceptionSerializationStrategy+<>c__DisplayClass14_0.<DescribeException>b__3(ExceptionDescriptor d)
    at System.Linq.Enumerable.TryGetFirst<TSource>(IEnumerable<T> source, Func<T, TResult> predicate, out bool found)
    at Amazon.XRay.Recorder.Core.Strategies.DefaultExceptionSerializationStrategy.DescribeException(Exception e, IEnumerable<T> subsegments)
    at Amazon.XRay.Recorder.Core.Internal.Entities.Entity.AddException(Exception e)
    at Amazon.XRay.Recorder.Core.AWSXRayRecorderImpl.AddException(Exception ex)
```

**Comment by scott-mcdonald** [comment]
Getting same error on awsxrayrecorder.core 2.10.1

System.NullReferenceException: {"Object reference not set to an instance of an object."}

```
   at Amazon.XRay.Recorder.Core.Strategies.DefaultExceptionSerializationStrategy.<>c__DisplayClass14_0.<DescribeException>b__3(ExceptionDescriptor d)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Amazon.XRay.Recorder.Core.Strategies.DefaultExceptionSerializationStrategy.DescribeException(Exception e, IEnumerable`1 subsegments)
   at Amazon.XRay.Recorder.Core.Internal.Entities.Entity.AddException(Exception e)
   at Amazon.XRay.Recorder.Core.AWSXRayRecorderImpl.AddException(Exception ex)

```
